export interface ApiEndpoint {
  id: string;
  provider: string;
  /** Base URL for the provider. Omit for ClawAPIs (default). */
  baseUrl?: string;
  /** API path on the provider. Omit only for legacy ClawAPIs endpoints. */
  path?: string;
  name: string;
  description: string;
  category: 'solana' | 'social' | 'utility' | 'defi' | 'intelligence' | 'oracle' | 'scraping' | 'discovery' | 'infrastructure' | 'search' | 'media' | 'enrichment' | 'weather' | 'ai-ml' | 'security';
  costPerCall: number;
  latencyMs: number;
  inputSchema: Record<string, string>;
  outputFields: string[];
  rateLimit?: number;
}

export const apiRegistry: ApiEndpoint[] = [

  // ─── ClawAPIs (primary provider via clawapis.com) ──────────────────────────

  {
    id: 'claw-token-metadata',
    provider: 'ClawAPIs',
    path: '/solscan/token/meta',
    name: 'Token Metadata',
    description: 'Get full metadata for a Solana token: name, symbol, decimals, supply, logo, description, social links.',
    category: 'solana',
    costPerCall: 0.001,
    latencyMs: 300,
    inputSchema: { mintAddress: 'Solana token mint address (base58)' },
    outputFields: ['name', 'symbol', 'decimals', 'totalSupply', 'logoURI', 'description', 'website', 'twitter'],
  },
  {
    id: 'claw-token-price',
    provider: 'ClawAPIs',
    path: '/solscan/token/meta',
    name: 'Token Price',
    description: 'Get current USD price, 24h change, volume, and market cap for a Solana token.',
    category: 'solana',
    costPerCall: 0.001,
    latencyMs: 200,
    inputSchema: { mintAddress: 'Solana token mint address (base58)' },
    outputFields: ['priceUsd', 'change24h', 'volume24h', 'marketCap', 'liquidity'],
  },
  {
    id: 'claw-token-holders',
    provider: 'ClawAPIs',
    path: '/solscan/token/holders',
    name: 'Token Holders',
    description: 'Get top holders of a Solana token, holder count, and concentration metrics. Useful for detecting whale risk.',
    category: 'solana',
    costPerCall: 0.002,
    latencyMs: 500,
    inputSchema: { mintAddress: 'Solana token mint address (base58)', limit: 'Number of top holders to return (default 20)' },
    outputFields: ['totalHolders', 'topHolders', 'top10Concentration', 'top25Concentration'],
  },
  {
    id: 'claw-token-risk',
    provider: 'ClawAPIs',
    path: '/solscan/token/meta',
    name: 'Token Risk Score',
    description: 'AI-powered rug pull risk analysis for a Solana token. Returns risk score 0-100 and specific risk flags.',
    category: 'solana',
    costPerCall: 0.003,
    latencyMs: 800,
    inputSchema: { mintAddress: 'Solana token mint address (base58)' },
    outputFields: ['riskScore', 'riskLevel', 'flags', 'mintAuthority', 'freezeAuthority', 'lpLocked'],
  },
  {
    id: 'claw-wallet-portfolio',
    provider: 'ClawAPIs',
    path: '/solscan/account/portfolio',
    name: 'Wallet Portfolio',
    description: 'Get all token holdings and their USD values for a Solana wallet address.',
    category: 'solana',
    costPerCall: 0.002,
    latencyMs: 600,
    inputSchema: { walletAddress: 'Solana wallet address (base58)' },
    outputFields: ['totalValueUsd', 'tokens', 'nfts', 'solBalance'],
  },
  {
    id: 'claw-tx-history',
    provider: 'ClawAPIs',
    path: '/solscan/account/transactions',
    name: 'Transaction History',
    description: 'Get recent transaction history for a Solana wallet. Shows swaps, transfers, and interactions.',
    category: 'solana',
    costPerCall: 0.002,
    latencyMs: 700,
    inputSchema: { walletAddress: 'Solana wallet address (base58)', limit: 'Number of transactions (default 20)' },
    outputFields: ['transactions', 'totalCount', 'swapCount', 'transferCount'],
  },
  {
    id: 'claw-trending-tokens',
    provider: 'ClawAPIs',
    path: '/solscan/token/trending',
    name: 'Trending Tokens',
    description: 'Get currently trending Solana tokens by volume, new listings, or social mentions. No input required.',
    category: 'solana',
    costPerCall: 0.001,
    latencyMs: 400,
    inputSchema: { sortBy: 'volume | new | social (default: volume)', limit: 'Number of results (default 10)' },
    outputFields: ['tokens', 'timestamp'],
  },
  {
    id: 'claw-x-mentions',
    provider: 'ClawAPIs',
    path: '/x/2/tweets/search/recent',
    name: 'X/Twitter Mentions',
    description: 'Get recent X/Twitter mentions, sentiment score, and engagement metrics for a token or topic.',
    category: 'social',
    costPerCall: 0.002,
    latencyMs: 600,
    inputSchema: { query: 'Token symbol, name, or search query', limit: 'Number of tweets (default 20)' },
    outputFields: ['mentionCount', 'sentimentScore', 'sentimentLabel', 'topTweets', 'engagementTotal'],
  },
  {
    id: 'claw-x-profile',
    provider: 'ClawAPIs',
    path: '/x/2/users/by/username',
    name: 'X/Twitter Profile',
    description: 'Get X/Twitter profile data for a username: followers, following, recent tweets, verification status.',
    category: 'social',
    costPerCall: 0.001,
    latencyMs: 400,
    inputSchema: { username: 'X/Twitter username without @' },
    outputFields: ['displayName', 'followers', 'following', 'verified', 'bio', 'recentTweets'],
  },
  {
    id: 'claw-reddit-sentiment',
    provider: 'ClawAPIs',
    path: '/x/2/tweets/search/recent',
    name: 'Reddit Sentiment',
    description: 'Analyze Reddit sentiment for a token or topic across relevant subreddits. Returns sentiment and top posts.',
    category: 'social',
    costPerCall: 0.002,
    latencyMs: 800,
    inputSchema: { query: 'Token symbol or topic to search', subreddits: 'Comma-separated subreddits (optional)' },
    outputFields: ['sentimentScore', 'sentimentLabel', 'postCount', 'topPosts', 'subredditsSearched'],
  },
  {
    id: 'claw-web-scrape',
    provider: 'ClawAPIs',
    path: '/solscan/token/list',
    name: 'Web Scrape',
    description: 'Scrape and extract clean text content from any public URL. Useful for reading whitepapers or project sites.',
    category: 'scraping',
    costPerCall: 0.005,
    latencyMs: 2000,
    inputSchema: { url: 'Full URL to scrape (must be publicly accessible)' },
    outputFields: ['title', 'content', 'links', 'images', 'wordCount'],
  },
  {
    id: 'claw-news-search',
    provider: 'ClawAPIs',
    path: '/x/2/tweets/search/recent',
    name: 'News Search',
    description: 'Search recent crypto and web3 news articles for a token, project, or topic. Returns headlines and summaries.',
    category: 'utility',
    costPerCall: 0.002,
    latencyMs: 600,
    inputSchema: { query: 'Search query (token name, project, topic)', limit: 'Number of articles (default 5)' },
    outputFields: ['articles', 'totalResults', 'query'],
  },
  {
    id: 'claw-wallet-risk',
    provider: 'ClawAPIs',
    path: '/solscan/account/detail',
    name: 'Wallet Risk Score',
    description: 'Analyze a Solana wallet for suspicious activity: wash trading, bot behavior, mixer interactions.',
    category: 'solana',
    costPerCall: 0.003,
    latencyMs: 900,
    inputSchema: { walletAddress: 'Solana wallet address (base58)' },
    outputFields: ['riskScore', 'riskLevel', 'flags', 'botProbability', 'mixerInteractions'],
  },

  // ─── CoinGecko x402 ────────────────────────────────────────────────────────
  // Experimental x402 endpoints — no API key required, pay-per-request
  {
    id: 'coingecko-price',
    provider: 'CoinGecko',
    baseUrl: 'https://pro-api.coingecko.com',
    path: '/api/v3/x402/simple/price',
    name: 'CoinGecko Token Price',
    description: 'Get authoritative crypto prices and market data for any token via CoinGecko x402. Supports multi-currency.',
    category: 'oracle',
    costPerCall: 0.001,
    latencyMs: 300,
    inputSchema: { ids: 'CoinGecko token ID (e.g. bitcoin, ethereum, solana)', vs_currencies: 'Currency codes (e.g. usd,eur)' },
    outputFields: ['price', 'market_cap', 'volume_24h', 'price_change_24h'],
  },
  {
    id: 'coingecko-coin-data',
    provider: 'CoinGecko',
    baseUrl: 'https://pro-api.coingecko.com',
    path: '/api/v3/x402/coins/markets',
    name: 'CoinGecko Market Data',
    description: 'Comprehensive market data for any cryptocurrency: price, volume, market cap, ATH, sparkline from CoinGecko.',
    category: 'oracle',
    costPerCall: 0.002,
    latencyMs: 500,
    inputSchema: { vs_currency: 'Quote currency (usd)', ids: 'CoinGecko IDs (comma-separated)', order: 'market_cap_desc | volume_desc' },
    outputFields: ['id', 'symbol', 'name', 'current_price', 'market_cap', 'total_volume', 'price_change_percentage_24h', 'ath'],
  },

  // ─── Rug Munch Intelligence ────────────────────────────────────────────────
  // 19 x402-paid endpoints for crypto risk intelligence
  {
    id: 'rugmunch-risk',
    provider: 'Rug Munch',
    baseUrl: 'https://cryptorugmunch.app',
    path: '/api/risk',
    name: 'Rug Munch Risk Score',
    description: 'AI-powered rug pull and scam risk score for any crypto token. Analyzes contract, holders, liquidity, and social signals.',
    category: 'intelligence',
    costPerCall: 0.003,
    latencyMs: 1000,
    inputSchema: { address: 'Token contract address', chain: 'Chain (solana | ethereum | base)' },
    outputFields: ['riskScore', 'riskLevel', 'flags', 'recommendation'],
  },
  {
    id: 'rugmunch-honeypot',
    provider: 'Rug Munch',
    baseUrl: 'https://cryptorugmunch.app',
    path: '/api/honeypot',
    name: 'Honeypot Detection',
    description: 'Detect if a token is a honeypot (cannot be sold after purchase). Returns simulation results and buy/sell tax.',
    category: 'intelligence',
    costPerCall: 0.002,
    latencyMs: 800,
    inputSchema: { address: 'Token contract address', chain: 'Chain (ethereum | base | solana)' },
    outputFields: ['isHoneypot', 'buyTax', 'sellTax', 'cannotSell', 'simulationResult'],
  },
  {
    id: 'rugmunch-holder-analysis',
    provider: 'Rug Munch',
    baseUrl: 'https://cryptorugmunch.app',
    path: '/api/holders',
    name: 'Holder Distribution Analysis',
    description: 'Deep holder concentration analysis: whale wallets, dev holdings, bundled wallets, and sybil patterns.',
    category: 'intelligence',
    costPerCall: 0.003,
    latencyMs: 1200,
    inputSchema: { address: 'Token contract address', chain: 'Chain identifier' },
    outputFields: ['holderCount', 'top10Pct', 'devWallets', 'bundledWallets', 'sybilRisk'],
  },

  // ─── Einstein AI ──────────────────────────────────────────────────────────
  // Blockchain intelligence: whale tracking, DEX analytics, MEV
  {
    id: 'einstein-whales',
    provider: 'Einstein AI',
    baseUrl: 'https://emc2ai.io',
    path: '/api/whales',
    name: 'Whale Tracking',
    description: 'Track smart money and whale wallets. See large token movements, accumulation patterns, and notable wallet activity.',
    category: 'intelligence',
    costPerCall: 0.004,
    latencyMs: 1000,
    inputSchema: { address: 'Token or wallet address', chain: 'Chain (ethereum | solana | base)', limit: 'Number of whale txns (default 10)' },
    outputFields: ['whaleMovements', 'netFlow', 'accumulators', 'distributors', 'smartMoneySignal'],
  },
  {
    id: 'einstein-dex',
    provider: 'Einstein AI',
    baseUrl: 'https://emc2ai.io',
    path: '/api/dex',
    name: 'DEX Analytics',
    description: 'Real-time DEX analytics: top pools, swap volumes, liquidity depth, price impact, and MEV activity for any token.',
    category: 'defi',
    costPerCall: 0.003,
    latencyMs: 800,
    inputSchema: { address: 'Token address', chain: 'Chain identifier', dex: 'DEX name (uniswap | raydium | jupiter — optional)' },
    outputFields: ['topPools', 'volume24h', 'liquidity', 'priceImpact', 'mevActivity'],
  },
  {
    id: 'einstein-mev',
    provider: 'Einstein AI',
    baseUrl: 'https://emc2ai.io',
    path: '/api/mev',
    name: 'MEV Detection',
    description: 'Detect MEV (sandwich attacks, frontrunning, arbitrage) targeting a specific token or transaction.',
    category: 'intelligence',
    costPerCall: 0.003,
    latencyMs: 900,
    inputSchema: { address: 'Token address or tx hash', chain: 'Chain identifier' },
    outputFields: ['mevDetected', 'attackType', 'victimLoss', 'attackerProfit', 'recentAttacks'],
  },

  // ─── Apollo Intelligence Network ──────────────────────────────────────────
  // 27 x402 endpoints: crypto prices, OSINT, DeFi yields, X search, proxies
  {
    id: 'apollo-prices',
    provider: 'Apollo Intelligence',
    baseUrl: 'https://apolloai.team',
    path: '/api/prices',
    name: 'Apollo Crypto Prices',
    description: 'Multi-source aggregated crypto prices with confidence scores and source attribution.',
    category: 'oracle',
    costPerCall: 0.001,
    latencyMs: 300,
    inputSchema: { symbols: 'Comma-separated token symbols (e.g. BTC,ETH,SOL)', currency: 'Quote currency (default: usd)' },
    outputFields: ['prices', 'sources', 'confidence', 'timestamp'],
  },
  {
    id: 'apollo-osint',
    provider: 'Apollo Intelligence',
    baseUrl: 'https://apolloai.team',
    path: '/api/osint',
    name: 'Apollo OSINT',
    description: 'OSINT intelligence on wallets, tokens, teams, and projects. Cross-references on-chain data with off-chain sources.',
    category: 'intelligence',
    costPerCall: 0.005,
    latencyMs: 1500,
    inputSchema: { target: 'Wallet address, token symbol, or project name', depth: 'shallow | deep (default: shallow)' },
    outputFields: ['entityType', 'associations', 'riskFlags', 'socialProfiles', 'onChainActivity'],
  },
  {
    id: 'apollo-defi-yields',
    provider: 'Apollo Intelligence',
    baseUrl: 'https://apolloai.team',
    path: '/api/yields',
    name: 'DeFi Yield Scanner',
    description: 'Scan top DeFi protocols for yield opportunities: APY, TVL, risk score, and impermanent loss estimates.',
    category: 'defi',
    costPerCall: 0.002,
    latencyMs: 600,
    inputSchema: { chain: 'Chain (ethereum | solana | base | all)', minApy: 'Minimum APY % filter (default 5)', token: 'Token to include (optional)' },
    outputFields: ['opportunities', 'bestApy', 'totalTvl', 'riskAdjustedYield'],
  },

  // ─── DiamondClaws DeFi Intelligence ───────────────────────────────────────
  // DeFi yield scoring, protocol risk, multi-chain gas oracles
  {
    id: 'diamondclaws-yield',
    provider: 'DiamondClaws',
    baseUrl: 'https://diamondclaws.xyz',
    path: '/api/yield',
    name: 'DeFi Yield Score',
    description: 'Risk-adjusted yield scoring for DeFi positions. Accounts for protocol risk, impermanent loss, and emission sustainability.',
    category: 'defi',
    costPerCall: 0.002,
    latencyMs: 700,
    inputSchema: { protocol: 'Protocol name or address', chain: 'Chain identifier', pool: 'Pool address or name (optional)' },
    outputFields: ['yieldScore', 'apy', 'riskAdjustedApy', 'impermanentLossRisk', 'sustainabilityScore'],
  },
  {
    id: 'diamondclaws-protocol-risk',
    provider: 'DiamondClaws',
    baseUrl: 'https://diamondclaws.xyz',
    path: '/api/protocol-risk',
    name: 'Protocol Risk Analysis',
    description: 'Security and risk analysis for DeFi protocols: audit history, TVL risk, centralization, and exploit probability.',
    category: 'defi',
    costPerCall: 0.003,
    latencyMs: 900,
    inputSchema: { protocol: 'Protocol name or contract address', chain: 'Chain identifier' },
    outputFields: ['riskScore', 'auditStatus', 'tvl', 'centralizationRisk', 'exploitHistory'],
  },
  {
    id: 'diamondclaws-gas',
    provider: 'DiamondClaws',
    baseUrl: 'https://diamondclaws.xyz',
    path: '/api/gas',
    name: 'Multi-Chain Gas Oracle',
    description: 'Real-time gas price oracle across Ethereum, Base, Arbitrum, Solana. Returns slow/standard/fast estimates.',
    category: 'oracle',
    costPerCall: 0.001,
    latencyMs: 200,
    inputSchema: { chain: 'Chain (ethereum | base | arbitrum | solana | all)' },
    outputFields: ['slow', 'standard', 'fast', 'unit', 'blockTime', 'baseFee'],
  },

  // ─── Elsa Finance ─────────────────────────────────────────────────────────
  // DeFi portfolio data, token prices, swap quotes, wallet analytics
  {
    id: 'elsa-portfolio',
    provider: 'Elsa Finance',
    baseUrl: 'https://elsa.finance',
    path: '/api/portfolio',
    name: 'DeFi Portfolio Overview',
    description: 'Complete DeFi portfolio snapshot: token balances, LP positions, staking rewards, and total value across chains.',
    category: 'defi',
    costPerCall: 0.003,
    latencyMs: 800,
    inputSchema: { wallet: 'Wallet address', chains: 'Chains to include (comma-separated, default: all)' },
    outputFields: ['totalValueUsd', 'tokens', 'lpPositions', 'stakingRewards', 'chainBreakdown'],
  },
  {
    id: 'elsa-swap-quote',
    provider: 'Elsa Finance',
    baseUrl: 'https://elsa.finance',
    path: '/api/swap-quote',
    name: 'Swap Quote',
    description: 'Best available swap quote across DEX aggregators. Returns price, slippage, fees, and optimal route.',
    category: 'defi',
    costPerCall: 0.002,
    latencyMs: 600,
    inputSchema: { fromToken: 'Source token address', toToken: 'Destination token address', amount: 'Amount to swap', chain: 'Chain identifier' },
    outputFields: ['expectedOut', 'priceImpact', 'fees', 'route', 'bestDex', 'slippagePct'],
  },

  // ─── SLAMai Smart Money ────────────────────────────────────────────────────
  // Smart-money intelligence on Base and Ethereum with MCP layer
  {
    id: 'slamai-signals',
    provider: 'SLAMai',
    baseUrl: 'https://slamai.io',
    path: '/api/signals',
    name: 'Smart Money Signals',
    description: 'Track smart money wallets and their recent positions. Identifies accumulation, exits, and alpha signals before they hit retail.',
    category: 'intelligence',
    costPerCall: 0.004,
    latencyMs: 900,
    inputSchema: { token: 'Token address or symbol', chain: 'Chain (ethereum | base)', lookback: 'Hours to look back (default 24)' },
    outputFields: ['smartMoneyNet', 'topBuyers', 'topSellers', 'signal', 'confidence'],
  },

  // ─── Automaton Oracle ─────────────────────────────────────────────────────
  // Sovereign crypto intelligence: prices, macro, pump.fun radar, signals
  {
    id: 'automaton-price',
    provider: 'Automaton Oracle',
    baseUrl: 'https://automaton-oracle.xyz',
    path: '/api/price',
    name: 'Automaton Price Feed',
    description: 'Sovereign crypto price feed with macro overlay. Returns price, trend, and macro context for any token.',
    category: 'oracle',
    costPerCall: 0.001,
    latencyMs: 300,
    inputSchema: { symbol: 'Token symbol (e.g. BTC, SOL)', currency: 'Quote currency (default: usd)' },
    outputFields: ['price', 'change24h', 'trend', 'macroContext', 'confidence'],
  },
  {
    id: 'automaton-signals',
    provider: 'Automaton Oracle',
    baseUrl: 'https://automaton-oracle.xyz',
    path: '/api/signals',
    name: 'Trading Signals',
    description: 'AI-generated trading signals with entry/exit points, risk levels, and reasoning for any crypto asset.',
    category: 'intelligence',
    costPerCall: 0.005,
    latencyMs: 1200,
    inputSchema: { symbol: 'Token symbol', timeframe: 'Timeframe (1h | 4h | 1d | 1w)' },
    outputFields: ['signal', 'direction', 'entryPrice', 'targets', 'stopLoss', 'confidence', 'reasoning'],
  },
  {
    id: 'automaton-pump-radar',
    provider: 'Automaton Oracle',
    baseUrl: 'https://automaton-oracle.xyz',
    path: '/api/pump-radar',
    name: 'Pump.fun Radar',
    description: 'Real-time pump.fun token radar: new launches, graduation candidates, and early-stage opportunity scoring.',
    category: 'intelligence',
    costPerCall: 0.002,
    latencyMs: 600,
    inputSchema: { filter: 'all | graduating | new | trending (default: trending)', limit: 'Number of results (default 20)' },
    outputFields: ['tokens', 'graduationCandidates', 'newLaunches', 'trendingNow'],
  },

  // ─── Crysha Price Oracle ──────────────────────────────────────────────────
  // Aggregated crypto price oracle with x402 micropayments
  {
    id: 'crysha-price',
    provider: 'Crysha',
    baseUrl: 'https://api.crysha.com',
    path: '/price',
    name: 'Crysha Aggregated Price',
    description: 'Aggregated crypto price oracle pulling from multiple exchanges. Returns VWAP price with source breakdown.',
    category: 'oracle',
    costPerCall: 0.001,
    latencyMs: 250,
    inputSchema: { symbol: 'Token symbol (e.g. BTC, ETH, SOL)', exchange: 'Exchange filter (optional, default: all)' },
    outputFields: ['price', 'vwap', 'sources', 'spread', 'timestamp'],
  },

  // ─── twit.sh (Real-time X/Twitter) ────────────────────────────────────────
  // Real-time Twitter/X data for AI agents, no signup required
  {
    id: 'twitsh-search',
    provider: 'twit.sh',
    baseUrl: 'https://twit.sh',
    path: '/api/search',
    name: 'Real-time X Search',
    description: 'Real-time Twitter/X search with no API key required. Returns tweets, engagement metrics, and sentiment.',
    category: 'social',
    costPerCall: 0.002,
    latencyMs: 600,
    inputSchema: { query: 'Search query or cashtag (e.g. $SOL or "solana")', limit: 'Max results (default 20)', lang: 'Language filter (optional, e.g. en)' },
    outputFields: ['tweets', 'mentionCount', 'engagementTotal', 'sentimentScore', 'topAccounts'],
  },
  {
    id: 'twitsh-user',
    provider: 'twit.sh',
    baseUrl: 'https://twit.sh',
    path: '/api/user',
    name: 'X User Profile',
    description: 'Real-time X/Twitter user profile data: followers, following, bio, recent tweets, and engagement rate.',
    category: 'social',
    costPerCall: 0.001,
    latencyMs: 400,
    inputSchema: { username: 'X/Twitter username without @' },
    outputFields: ['displayName', 'followers', 'following', 'bio', 'verified', 'recentTweets', 'engagementRate'],
  },

  // ─── Gloria AI (News Intelligence) ────────────────────────────────────────
  // Real-time, structured, high-signal news data for AI agents
  {
    id: 'gloria-news',
    provider: 'Gloria AI',
    baseUrl: 'https://gloriaai.xyz',
    path: '/api/news',
    name: 'Crypto News Feed',
    description: 'High-signal crypto news with AI-generated summaries, sentiment scores, and market impact assessment.',
    category: 'utility',
    costPerCall: 0.002,
    latencyMs: 500,
    inputSchema: { query: 'Topic, token name, or keyword', limit: 'Number of articles (default 10)', sentiment: 'Filter by sentiment: positive | negative | neutral (optional)' },
    outputFields: ['articles', 'topHeadlines', 'sentimentBreakdown', 'marketImpact'],
  },

  // ─── Olostep (Web Scraping + Answers) ─────────────────────────────────────
  // Pay-per-use x402 access for maps, scrapes, crawls, and answers
  {
    id: 'olostep-scrape',
    provider: 'Olostep',
    baseUrl: 'https://api.olostep.com',
    path: '/x402/scrape',
    name: 'Web Page Scrape',
    description: 'Extract clean, LLM-ready content from any web page. Returns markdown text, structured data, and metadata.',
    category: 'scraping',
    costPerCall: 0.003,
    latencyMs: 1500,
    inputSchema: { url: 'Full URL to scrape', format: 'markdown | html | json (default: markdown)', waitFor: 'CSS selector to wait for (optional)' },
    outputFields: ['content', 'title', 'metadata', 'links', 'wordCount'],
  },
  {
    id: 'olostep-answers',
    provider: 'Olostep',
    baseUrl: 'https://api.olostep.com',
    path: '/x402/answers',
    name: 'Web Answers',
    description: 'Ask a question and get an AI answer grounded in live web data. Returns answer with source citations.',
    category: 'utility',
    costPerCall: 0.008,
    latencyMs: 3000,
    inputSchema: { question: 'Question to answer using live web data', context: 'Additional context (optional)' },
    outputFields: ['answer', 'sources', 'confidence', 'relatedQuestions'],
  },

  // ─── Minifetch (Token-efficient Web Summaries) ─────────────────────────────
  // Structured metadata and token-efficient summaries via micropayments
  {
    id: 'minifetch-summary',
    provider: 'Minifetch',
    baseUrl: 'https://minifetch.dev',
    path: '/api/summary',
    name: 'Web Page Summary',
    description: 'Fetch structured metadata and a token-efficient AI summary from any URL. Ideal for whitepapers and project sites.',
    category: 'scraping',
    costPerCall: 0.002,
    latencyMs: 1000,
    inputSchema: { url: 'Full URL to summarize', maxTokens: 'Max summary tokens (default 200)', focus: 'Key aspect to focus on (optional)' },
    outputFields: ['summary', 'title', 'description', 'keywords', 'ogImage', 'publishDate'],
  },

  // ─── Pylon API Gateway ────────────────────────────────────────────────────
  // x402-payable utility gateway: web extraction, search, translation, code
  {
    id: 'pylon-search',
    provider: 'Pylon',
    baseUrl: 'https://pylonapi.com',
    path: '/api/search',
    name: 'Pylon Web Search',
    description: 'Real-time web search with structured results. Returns titles, URLs, snippets, and AI-summarized answer.',
    category: 'utility',
    costPerCall: 0.003,
    latencyMs: 800,
    inputSchema: { query: 'Search query', limit: 'Number of results (default 10)', lang: 'Language (default: en)' },
    outputFields: ['results', 'answer', 'relatedSearches', 'totalResults'],
  },
  {
    id: 'pylon-extract',
    provider: 'Pylon',
    baseUrl: 'https://pylonapi.com',
    path: '/api/extract',
    name: 'Pylon Web Extraction',
    description: 'Structured data extraction from any URL using AI. Returns clean text, tables, prices, and entities.',
    category: 'scraping',
    costPerCall: 0.004,
    latencyMs: 1200,
    inputSchema: { url: 'URL to extract from', schema: 'Data schema to extract (optional JSON schema)', type: 'text | structured | auto (default: auto)' },
    outputFields: ['text', 'structured', 'entities', 'tables', 'confidence'],
  },

  // ─── Browserbase (Pay-per-use Browser Sessions) ────────────────────────────
  // Full browser sessions for JS-heavy sites and dynamic content
  {
    id: 'browserbase-session',
    provider: 'Browserbase',
    baseUrl: 'https://x402.browserbase.com',
    path: '/v1/sessions',
    name: 'Browser Session',
    description: 'Spin up a managed browser session to interact with JS-heavy sites, login walls, and dynamic content.',
    category: 'scraping',
    costPerCall: 0.010,
    latencyMs: 3000,
    inputSchema: { url: 'Starting URL for the browser session', timeout: 'Session timeout in seconds (default 30)', action: 'Action to perform (screenshot | scrape | interact)' },
    outputFields: ['sessionId', 'screenshot', 'content', 'cookies', 'networkRequests'],
  },

  // ─── BlackSwan Risk Intelligence ──────────────────────────────────────────
  // Real-time risk intelligence infrastructure for autonomous AI agents
  {
    id: 'blackswan-risk',
    provider: 'BlackSwan',
    baseUrl: 'https://blackswan.wtf',
    path: '/api/risk',
    name: 'BlackSwan Risk Intelligence',
    description: 'Real-time tail risk and black swan event detection for crypto markets. Returns systemic risk score and early warning signals.',
    category: 'intelligence',
    costPerCall: 0.005,
    latencyMs: 1000,
    inputSchema: { asset: 'Asset symbol or address', timeframe: 'Risk horizon (1h | 24h | 7d)', chain: 'Chain identifier (optional)' },
    outputFields: ['riskScore', 'riskLevel', 'earlyWarnings', 'systemicRisk', 'correlations'],
  },

  // ─── Moltalyzer ───────────────────────────────────────────────────────────
  // Community digests, GitHub trending, Polymarket, token intelligence
  {
    id: 'moltalyzer-token-intel',
    provider: 'Moltalyzer',
    baseUrl: 'https://moltalyzer.xyz',
    path: '/api/token',
    name: 'Moltalyzer Token Intelligence',
    description: 'Aggregated token intelligence: community digest, GitHub activity, Polymarket odds, and AI-generated outlook.',
    category: 'intelligence',
    costPerCall: 0.003,
    latencyMs: 900,
    inputSchema: { token: 'Token symbol or address', include: 'community | github | polymarket | all (default: all)' },
    outputFields: ['communityDigest', 'githubActivity', 'polymarketOdds', 'outlook', 'sentimentScore'],
  },

  // ─── CrossFin (Korean Market Intelligence) ────────────────────────────────
  // Korean market: Kimchi premium, exchanges, FX, headlines, signals
  {
    id: 'crossfin-kimchi',
    provider: 'CrossFin',
    baseUrl: 'https://crossfin.dev',
    path: '/api/kimchi',
    name: 'Kimchi Premium',
    description: 'Korean crypto Kimchi premium index — price differential between Korean exchanges and global market. Key arbitrage signal.',
    category: 'oracle',
    costPerCall: 0.002,
    latencyMs: 400,
    inputSchema: { symbol: 'Token symbol (e.g. BTC, ETH)', exchange: 'Korean exchange (upbit | bithumb | all, default: all)' },
    outputFields: ['kimchiPremium', 'koreanPrice', 'globalPrice', 'spread', 'trend'],
  },

  // ─── Messari ──────────────────────────────────────────────────────────────
  // Pay-per-request Messari data: AI, funds, organizations, projects, markets
  {
    id: 'messari-asset',
    provider: 'Messari',
    baseUrl: 'https://api.messari.io',
    path: '/api/v1/assets',
    name: 'Messari Asset Data',
    description: 'Comprehensive asset data from Messari research: fundamentals, market data, investor info, and qualitative analysis.',
    category: 'intelligence',
    costPerCall: 0.004,
    latencyMs: 800,
    inputSchema: { symbol: 'Token symbol or name', fields: 'Fields to include (optional, comma-separated)' },
    outputFields: ['name', 'symbol', 'category', 'sector', 'marketcap', 'volume', 'fundamentals', 'investors'],
  },

  // ─── x402 Service Discovery ────────────────────────────────────────────────
  // Enriched x402 service directory with trust signals and health scores
  {
    id: 'x402-discover',
    provider: 'x402 Discovery API',
    baseUrl: 'https://x402-discovery-api.onrender.com',
    path: '/services',
    name: 'x402 Service Discovery',
    description: 'Search the x402 service registry for APIs matching a capability. Returns ranked list with uptime, latency, and trust scores.',
    category: 'discovery',
    costPerCall: 0.001,
    latencyMs: 500,
    inputSchema: { query: 'Capability or service type to search (e.g. "price oracle" or "web scraping")', chain: 'Payment chain filter (solana | base | all)' },
    outputFields: ['services', 'totalFound', 'bestMatch', 'averageUptime', 'averageLatency'],
  },
  {
    id: 'x402-route',
    provider: 'x402 RouteNet',
    baseUrl: 'https://x402-routenet.onrender.com',
    path: '/route',
    name: 'x402 Smart Route',
    description: 'Smart routing layer for x402 services. Given a capability, returns the best/cheapest/fastest provider.',
    category: 'discovery',
    costPerCall: 0.001,
    latencyMs: 400,
    inputSchema: { capability: 'Capability needed (e.g. token price, web scrape)', strategy: 'best | cheapest | fastest | most_trusted (default: best)' },
    outputFields: ['selectedProvider', 'endpoint', 'estimatedCost', 'estimatedLatency', 'alternatives'],
  },

  // ─── PayAI Facilitator ────────────────────────────────────────────────────
  // Solana-first, multi-network x402 facilitator and discovery
  {
    id: 'payai-discovery',
    provider: 'PayAI',
    baseUrl: 'https://facilitator.payai.network',
    path: '/discovery/resources',
    name: 'PayAI Resource Discovery',
    description: 'Discover x402-compatible API resources across all supported networks from the PayAI facilitator.',
    category: 'discovery',
    costPerCall: 0.001,
    latencyMs: 500,
    inputSchema: { network: 'Filter by network (solana | base | ethereum | all)', category: 'Resource category filter (optional)' },
    outputFields: ['resources', 'totalCount', 'networks', 'categories'],
  },

  // ─── claw402.ai Gateway ───────────────────────────────────────────────────
  // All routes below go through https://claw402.ai (USDC on Base, ~$0.001/call)
  // NOTE: LLM wrapper endpoints (OpenAI, Anthropic, Deepseek, Qwen) are
  // intentionally excluded: they create recursive orchestration loops,
  // unpredictable costs ($0.12–$0.50/call), and prompt-injection surfaces.

  // nofxos — AI-coin rankings & net-flow analytics (18 endpoints, subset below)
  {
    id: 'nofxos-ai500',
    provider: 'nofxos',
    baseUrl: 'https://claw402.ai',
    path: '/api/v1/nofx/ai500/list',
    name: 'AI500 Coin List',
    description: 'Top 500 AI-related crypto coins ranked by composite score including price momentum, dev activity, and community growth.',
    category: 'intelligence',
    costPerCall: 0.001,
    latencyMs: 400,
    inputSchema: { limit: 'Number of results (default 50)', sort: 'Sort field (default: composite_score)' },
    outputFields: ['coins', 'totalCount', 'lastUpdated'],
  },
  {
    id: 'nofxos-ai300',
    provider: 'nofxos',
    baseUrl: 'https://claw402.ai',
    path: '/api/v1/nofx/ai300/list',
    name: 'AI300 Coin List',
    description: 'Curated list of 300 top AI-narrative coins with composite scores, open interest, and net-flow signals.',
    category: 'intelligence',
    costPerCall: 0.001,
    latencyMs: 400,
    inputSchema: { limit: 'Number of results (default 50)' },
    outputFields: ['coins', 'totalCount', 'lastUpdated'],
  },
  {
    id: 'nofxos-netflow',
    provider: 'nofxos',
    baseUrl: 'https://claw402.ai',
    path: '/api/v1/nofx/netflow/top-ranking',
    name: 'Net Flow Top Ranking',
    description: 'Top tokens ranked by net capital flow (inflow minus outflow). Identifies where smart money is moving right now.',
    category: 'intelligence',
    costPerCall: 0.001,
    latencyMs: 400,
    inputSchema: { timeframe: 'Time window (1h | 4h | 24h, default: 24h)', limit: 'Number of results (default 20)' },
    outputFields: ['tokens', 'topInflow', 'topOutflow', 'marketNetFlow'],
  },

  // RootData — VC/funding/project intelligence (19 endpoints, subset below)
  {
    id: 'rootdata-search',
    provider: 'RootData',
    baseUrl: 'https://claw402.ai',
    path: '/api/v1/crypto/rootdata/search',
    name: 'RootData Project Search',
    description: 'Search RootData database for crypto projects, VCs, people, and organizations. Returns funding history and investor details.',
    category: 'intelligence',
    costPerCall: 0.003,
    latencyMs: 800,
    inputSchema: { query: 'Project name, VC name, or person', type: 'project | vc | person | all (default: all)' },
    outputFields: ['projects', 'vcs', 'people', 'totalResults'],
  },
  {
    id: 'rootdata-funding',
    provider: 'RootData',
    baseUrl: 'https://claw402.ai',
    path: '/api/v1/crypto/rootdata/funding',
    name: 'RootData Funding Rounds',
    description: 'Recent crypto funding rounds with amount, lead investors, valuation, and project category from RootData.',
    category: 'intelligence',
    costPerCall: 0.003,
    latencyMs: 800,
    inputSchema: { project: 'Project name or ID (optional)', limit: 'Number of rounds (default 20)', minAmount: 'Minimum round size in USD (optional)' },
    outputFields: ['rounds', 'totalRaised', 'topInvestors', 'averageValuation'],
  },
  {
    id: 'rootdata-hot-x',
    provider: 'RootData',
    baseUrl: 'https://claw402.ai',
    path: '/api/v1/crypto/rootdata/hot-x',
    name: 'RootData Hot X Projects',
    description: 'Trending crypto projects on X/Twitter by engagement, investor mentions, and narrative momentum from RootData.',
    category: 'intelligence',
    costPerCall: 0.002,
    latencyMs: 600,
    inputSchema: { limit: 'Number of projects (default 20)', category: 'Narrative category filter (optional)' },
    outputFields: ['projects', 'trendingNarratives', 'hotInvestors', 'lastUpdated'],
  },

  // CoinAnk — 78-endpoint crypto market analytics (key subset below)
  {
    id: 'coinank-kline',
    provider: 'CoinAnk',
    baseUrl: 'https://claw402.ai',
    path: '/api/v1/coinank/kline/lists',
    name: 'CoinAnk Candlestick Data',
    description: 'OHLCV candlestick data for any crypto pair across spot and perpetual markets from multiple exchanges.',
    category: 'oracle',
    costPerCall: 0.001,
    latencyMs: 300,
    inputSchema: { symbol: 'Trading pair (e.g. BTC/USDT)', exchange: 'Exchange (binance | okx | bybit | all)', interval: 'Interval (1m | 5m | 1h | 4h | 1d)', size: 'Number of candles (default 100)', productType: 'swap | spot (default: spot)' },
    outputFields: ['candles', 'symbol', 'exchange', 'interval', 'openTime', 'closeTime'],
  },
  {
    id: 'coinank-btc-etf-inflow',
    provider: 'CoinAnk',
    baseUrl: 'https://claw402.ai',
    path: '/api/v1/coinank/etf/us-btc-inflow',
    name: 'BTC ETF Inflows',
    description: 'US spot Bitcoin ETF daily inflow/outflow data by issuer (BlackRock, Fidelity, etc.). Critical macro signal.',
    category: 'intelligence',
    costPerCall: 0.001,
    latencyMs: 400,
    inputSchema: { date: 'Date (YYYY-MM-DD, default: latest)', issuer: 'ETF issuer filter (optional, e.g. blackrock)' },
    outputFields: ['totalNetFlow', 'byIssuer', 'totalAUM', 'date', 'cumulativeInflow'],
  },
  {
    id: 'coinank-hyper-position',
    provider: 'CoinAnk',
    baseUrl: 'https://claw402.ai',
    path: '/api/v1/coinank/hyper/top-position',
    name: 'HyperLiquid Top Positions',
    description: 'Top whale positions on HyperLiquid DEX: largest open positions, PnL, leverage, and asset breakdown.',
    category: 'intelligence',
    costPerCall: 0.001,
    latencyMs: 400,
    inputSchema: { limit: 'Number of positions (default 20)', asset: 'Asset filter (optional, e.g. BTC)' },
    outputFields: ['positions', 'totalOI', 'largestPositions', 'topGainers', 'topLosers'],
  },
  {
    id: 'coinank-liquidation-map',
    provider: 'CoinAnk',
    baseUrl: 'https://claw402.ai',
    path: '/api/v1/coinank/liquidation/heat-map',
    name: 'Liquidation Heat Map',
    description: 'Crypto liquidation heat map: price levels with highest liquidation concentration across exchanges and assets.',
    category: 'intelligence',
    costPerCall: 0.001,
    latencyMs: 400,
    inputSchema: { symbol: 'Asset (e.g. BTC, ETH)', exchange: 'Exchange (binance | bybit | all, default: all)', timeframe: '12h | 24h | 3d | 7d (default: 24h)' },
    outputFields: ['liquidationMap', 'nextKeyLevel', 'longLiquidations', 'shortLiquidations', 'totalAtRisk'],
  },
  {
    id: 'coinank-funding-rate',
    provider: 'CoinAnk',
    baseUrl: 'https://claw402.ai',
    path: '/api/v1/coinank/funding/rate',
    name: 'Funding Rate Data',
    description: 'Perpetual futures funding rates across exchanges. High positive = crowded longs; negative = crowded shorts.',
    category: 'oracle',
    costPerCall: 0.001,
    latencyMs: 300,
    inputSchema: { symbol: 'Asset symbol (e.g. BTC)', exchange: 'Exchange filter (optional)', limit: 'Number of results (default 20)' },
    outputFields: ['fundingRate', 'annualizedRate', 'nextFundingTime', 'byExchange'],
  },
  {
    id: 'coinank-fear-greed',
    provider: 'CoinAnk',
    baseUrl: 'https://claw402.ai',
    path: '/api/v1/coinank/fear-greed/index',
    name: 'Fear & Greed Index',
    description: 'Crypto market Fear & Greed Index with historical data. Composite of volatility, volume, social, and momentum signals.',
    category: 'oracle',
    costPerCall: 0.001,
    latencyMs: 250,
    inputSchema: { days: 'Days of history (default 1, max 90)' },
    outputFields: ['value', 'classification', 'timestamp', 'history'],
  },
  {
    id: 'coinank-long-short',
    provider: 'CoinAnk',
    baseUrl: 'https://claw402.ai',
    path: '/api/v1/coinank/long-short/ratio',
    name: 'Long/Short Ratio',
    description: 'Exchange-wide long/short position ratios for any asset. Key sentiment and contrarian trading signal.',
    category: 'intelligence',
    costPerCall: 0.001,
    latencyMs: 300,
    inputSchema: { symbol: 'Asset symbol (e.g. BTC)', exchange: 'Exchange (binance | okx | bybit)', interval: '1h | 4h | 1d (default: 1h)', limit: 'Periods of history (default 24)' },
    outputFields: ['longRatio', 'shortRatio', 'longShortRatio', 'history'],
  },

  // CoinMarketCap (via claw402.ai)
  {
    id: 'cmc-quotes',
    provider: 'CoinMarketCap',
    baseUrl: 'https://claw402.ai',
    path: '/api/v1/coinmarketcap/quotes/latest',
    name: 'CMC Latest Quotes',
    description: 'Latest price quotes, volume, and market cap from CoinMarketCap. Authoritative market data for any cryptocurrency.',
    category: 'oracle',
    costPerCall: 0.001,
    latencyMs: 300,
    inputSchema: { symbol: 'Comma-separated token symbols (e.g. BTC,ETH,SOL)', convert: 'Quote currency (default: USD)' },
    outputFields: ['price', 'volume24h', 'marketCap', 'percentChange24h', 'rank', 'circulatingSupply'],
  },
  {
    id: 'cmc-rankings',
    provider: 'CoinMarketCap',
    baseUrl: 'https://claw402.ai',
    path: '/api/v1/coinmarketcap/listings/latest',
    name: 'CMC Market Rankings',
    description: 'Latest market cap rankings from CoinMarketCap. Returns top N crypto assets sorted by market cap.',
    category: 'oracle',
    costPerCall: 0.001,
    latencyMs: 300,
    inputSchema: { limit: 'Number of results (default 100, max 5000)', start: 'Starting rank (default 1)', convert: 'Quote currency (default: USD)' },
    outputFields: ['coins', 'totalActive', 'lastUpdated'],
  },

  // Alpha Vantage (via claw402.ai) — US stocks & technical indicators
  {
    id: 'alphavantage-stock',
    provider: 'Alpha Vantage',
    baseUrl: 'https://claw402.ai',
    path: '/api/v1/alphavantage/stock/quote',
    name: 'US Stock Quote',
    description: 'Real-time US stock quote from Alpha Vantage: price, volume, open, high, low, and change percentage.',
    category: 'oracle',
    costPerCall: 0.001,
    latencyMs: 400,
    inputSchema: { symbol: 'Stock ticker (e.g. AAPL, TSLA, NVDA)' },
    outputFields: ['price', 'open', 'high', 'low', 'volume', 'change', 'changePercent', 'latestTradingDay'],
  },
  {
    id: 'alphavantage-technical',
    provider: 'Alpha Vantage',
    baseUrl: 'https://claw402.ai',
    path: '/api/v1/alphavantage/technical',
    name: 'Technical Indicator',
    description: 'Technical analysis indicators (RSI, MACD, SMA, EMA, Bollinger Bands) for stocks and forex via Alpha Vantage.',
    category: 'oracle',
    costPerCall: 0.002,
    latencyMs: 500,
    inputSchema: { symbol: 'Ticker symbol', indicator: 'RSI | MACD | SMA | EMA | BBANDS', interval: 'daily | weekly | 60min | 30min', time_period: 'Periods for calculation (default 14)' },
    outputFields: ['values', 'indicator', 'lastRefreshed'],
  },

  // Alpaca (via claw402.ai) — US equities & options
  {
    id: 'alpaca-stock-bars',
    provider: 'Alpaca',
    baseUrl: 'https://claw402.ai',
    path: '/api/v1/alpaca/stocks/bars',
    name: 'Alpaca Stock Bars',
    description: 'Historical OHLCV bars for US stocks from Alpaca. Supports minute, hour, and daily timeframes.',
    category: 'oracle',
    costPerCall: 0.001,
    latencyMs: 400,
    inputSchema: { symbol: 'Stock ticker (e.g. AAPL)', timeframe: '1Min | 5Min | 1Hour | 1Day', start: 'Start date (YYYY-MM-DD)', end: 'End date (YYYY-MM-DD, default: today)', limit: 'Max bars (default 100)' },
    outputFields: ['bars', 'symbol', 'timeframe', 'nextPageToken'],
  },

  // Polygon.io (via claw402.ai) — tick data & fundamentals
  {
    id: 'polygon-ticker',
    provider: 'Polygon.io',
    baseUrl: 'https://claw402.ai',
    path: '/api/v1/polygon/ticker/details',
    name: 'Polygon Ticker Details',
    description: 'Comprehensive ticker details for US stocks from Polygon.io: company info, SIC code, market cap, and share class data.',
    category: 'intelligence',
    costPerCall: 0.001,
    latencyMs: 300,
    inputSchema: { ticker: 'Stock ticker (e.g. AAPL)', date: 'As-of date (YYYY-MM-DD, optional)' },
    outputFields: ['name', 'ticker', 'market', 'locale', 'type', 'currency', 'marketCap', 'sharesOutstanding'],
  },
  {
    id: 'polygon-aggregates',
    provider: 'Polygon.io',
    baseUrl: 'https://claw402.ai',
    path: '/api/v1/polygon/aggregates',
    name: 'Polygon Aggregate Bars',
    description: 'Aggregate OHLCV bars for any US stock from Polygon.io with split/dividend adjustment and tick-level accuracy.',
    category: 'oracle',
    costPerCall: 0.001,
    latencyMs: 400,
    inputSchema: { ticker: 'Stock ticker', multiplier: 'Bar size multiplier (e.g. 1, 5)', timespan: 'minute | hour | day | week', from: 'Start date (YYYY-MM-DD)', to: 'End date (YYYY-MM-DD)', limit: 'Max results (default 120)' },
    outputFields: ['results', 'ticker', 'queryCount', 'resultsCount', 'adjusted'],
  },

  // TwelveData (via claw402.ai) — forex, metals, indices
  {
    id: 'twelvedata-price',
    provider: 'TwelveData',
    baseUrl: 'https://claw402.ai',
    path: '/api/v1/twelvedata/price',
    name: 'TwelveData Real-time Price',
    description: 'Real-time price for forex pairs, metals, indices, and stocks from TwelveData. Global coverage including XAU, XAG.',
    category: 'oracle',
    costPerCall: 0.001,
    latencyMs: 250,
    inputSchema: { symbol: 'Symbol (e.g. EUR/USD, XAU/USD, SPX, AAPL)' },
    outputFields: ['price', 'symbol', 'timestamp'],
  },
  {
    id: 'twelvedata-time-series',
    provider: 'TwelveData',
    baseUrl: 'https://claw402.ai',
    path: '/api/v1/twelvedata/time_series',
    name: 'TwelveData Time Series',
    description: 'OHLCV time series for forex, metals, indices, and equities via TwelveData. Includes economic calendar data.',
    category: 'oracle',
    costPerCall: 0.002,
    latencyMs: 400,
    inputSchema: { symbol: 'Symbol (e.g. EUR/USD, XAU/USD)', interval: '1min | 5min | 1h | 1day | 1week', outputsize: 'Number of bars (default 30)', start_date: 'Start date (optional)', end_date: 'End date (optional)' },
    outputFields: ['values', 'meta', 'status'],
  },

  // x402 Ecosystem Analytics
  {
    id: 'x402list-search',
    provider: 'x402list.fun',
    baseUrl: 'https://x402list.fun',
    path: '/api/search',
    name: 'x402 Ecosystem Search',
    description: 'Search the full x402 ecosystem: all providers, endpoints, pricing, volume, and reliability metrics.',
    category: 'discovery',
    costPerCall: 0.001,
    latencyMs: 500,
    inputSchema: { query: 'Capability or provider to search', sort: 'reliability | price | volume (default: reliability)' },
    outputFields: ['providers', 'endpoints', 'totalResults', 'averagePrice'],
  },
  {
    id: 'x402scan-tx',
    provider: 'x402scan',
    baseUrl: 'https://x402scan.xyz',
    path: '/api/transactions',
    name: 'x402 Transaction Analytics',
    description: 'x402 payment transaction explorer: volume, top providers, payment chains, and ecosystem health metrics.',
    category: 'discovery',
    costPerCall: 0.001,
    latencyMs: 500,
    inputSchema: { provider: 'Filter by provider (optional)', chain: 'Payment chain (solana | base | all)', limit: 'Number of transactions (default 20)' },
    outputFields: ['transactions', 'totalVolume', 'activeProviders', 'topEndpoints'],
  },
  {
    id: 'x402station-monitor',
    provider: 'x402station',
    baseUrl: 'https://x402station.io',
    path: '/api/status',
    name: 'x402 Service Monitor',
    description: 'Real-time health and uptime monitoring for x402 services. Check which providers are up, degraded, or down.',
    category: 'discovery',
    costPerCall: 0.001,
    latencyMs: 300,
    inputSchema: { provider: 'Specific provider to check (optional, default: all)' },
    outputFields: ['services', 'uptimePct', 'avgLatency', 'incidentCount', 'healthScore'],
  },

  // ─── Pinata (x402 IPFS storage) ────────────────────────────────────────────

  {
    id: 'pinata-pin-public',
    provider: 'Pinata',
    baseUrl: 'https://402.pinata.cloud/v1',
    path: '/pin/public',
    name: 'Pinata Pin Public',
    description: 'Pin a file to public IPFS via Pinata using x402 micropayments. No API key required. Price scales with file size ($0.10/GB/year).',
    category: 'infrastructure',
    costPerCall: 0.01,
    latencyMs: 800,
    inputSchema: { file: 'File content or URL to pin', name: 'Optional name for the pin' },
    outputFields: ['cid', 'size', 'timestamp', 'pinataUrl'],
  },
  {
    id: 'pinata-pin-private',
    provider: 'Pinata',
    baseUrl: 'https://402.pinata.cloud/v1',
    path: '/pin/private',
    name: 'Pinata Pin Private',
    description: 'Pin a file to private encrypted IPFS storage via Pinata. Only accessible with wallet authorization.',
    category: 'infrastructure',
    costPerCall: 0.01,
    latencyMs: 800,
    inputSchema: { file: 'File content or URL to pin', name: 'Optional name for the pin' },
    outputFields: ['cid', 'size', 'timestamp', 'accessUrl'],
  },
  {
    id: 'pinata-retrieve',
    provider: 'Pinata',
    baseUrl: 'https://402.pinata.cloud/v1',
    path: '/retrieve/private',
    name: 'Pinata Retrieve Private',
    description: 'Retrieve a privately stored IPFS file by CID via Pinata x402. Costs $0.0001 per retrieval.',
    category: 'infrastructure',
    costPerCall: 0.0001,
    latencyMs: 500,
    inputSchema: { cid: 'IPFS Content Identifier (CID) to retrieve' },
    outputFields: ['content', 'size', 'mimeType', 'downloadUrl'],
  },

  // ─── Firecrawl (web scraping + search) ─────────────────────────────────────

  {
    id: 'firecrawl-scrape',
    provider: 'Firecrawl',
    baseUrl: 'https://api.firecrawl.dev/v1/x402',
    path: '/scrape',
    name: 'Firecrawl Scrape',
    description: 'Scrape any URL and return clean LLM-ready markdown. Handles JS rendering, bot bypass, and content extraction.',
    category: 'scraping',
    costPerCall: 0.01,
    latencyMs: 2000,
    inputSchema: { url: 'URL to scrape', formats: 'Output formats: markdown | html | links | screenshot (default: markdown)', onlyMainContent: 'Strip nav/footer/ads (default: true)' },
    outputFields: ['markdown', 'html', 'links', 'metadata', 'screenshot'],
  },
  {
    id: 'firecrawl-crawl',
    provider: 'Firecrawl',
    baseUrl: 'https://api.firecrawl.dev/v1/x402',
    path: '/crawl',
    name: 'Firecrawl Crawl',
    description: 'Crawl an entire website and return all pages as clean markdown. Follows links, respects robots.txt.',
    category: 'scraping',
    costPerCall: 0.05,
    latencyMs: 5000,
    inputSchema: { url: 'Base URL to crawl', limit: 'Max pages to crawl (default 10)', excludePaths: 'URL patterns to exclude' },
    outputFields: ['pages', 'totalCount', 'creditsUsed', 'status'],
  },
  {
    id: 'firecrawl-search',
    provider: 'Firecrawl',
    baseUrl: 'https://api.firecrawl.dev/v1/x402',
    path: '/search',
    name: 'Firecrawl Search',
    description: 'Web search with automatic scraping of each result. Returns search results as clean markdown, ready for LLM processing. $0.01/request.',
    category: 'search',
    costPerCall: 0.01,
    latencyMs: 3000,
    inputSchema: { query: 'Search query', limit: 'Number of results to scrape (default 5)', lang: 'Language code (default: en)' },
    outputFields: ['results', 'query', 'totalResults'],
  },
  {
    id: 'firecrawl-map',
    provider: 'Firecrawl',
    baseUrl: 'https://api.firecrawl.dev/v1/x402',
    path: '/map',
    name: 'Firecrawl Map',
    description: 'Map all URLs on a website quickly without scraping content. Returns full site structure and link graph.',
    category: 'scraping',
    costPerCall: 0.005,
    latencyMs: 1500,
    inputSchema: { url: 'Base URL to map', limit: 'Max URLs (default 100)', includeSubdomains: 'Include subdomains (default: false)' },
    outputFields: ['links', 'totalLinks', 'sitemapUrl'],
  },

  // ─── cnvrt.ing (media conversion) ──────────────────────────────────────────

  {
    id: 'cnvrt-convert',
    provider: 'cnvrt.ing',
    baseUrl: 'https://cnvrt.ing',
    path: '/api/convert',
    name: 'Media Convert',
    description: 'Convert media files between formats: video, audio, images. Supports 50+ format pairs via x402 micropayments.',
    category: 'media',
    costPerCall: 0.02,
    latencyMs: 3000,
    inputSchema: { fileUrl: 'URL of file to convert', targetFormat: 'Output format (mp4, mp3, webp, pdf, etc.)' },
    outputFields: ['outputUrl', 'size', 'duration', 'format'],
  },
  {
    id: 'cnvrt-transcribe',
    provider: 'cnvrt.ing',
    baseUrl: 'https://cnvrt.ing',
    path: '/api/transcribe',
    name: 'Audio Transcription',
    description: 'Transcribe audio or video files to text. Supports 50+ languages with speaker diarization and timestamps.',
    category: 'media',
    costPerCall: 0.03,
    latencyMs: 4000,
    inputSchema: { fileUrl: 'URL of audio/video file', language: 'Language code (default: auto)', diarize: 'Speaker diarization (default: false)' },
    outputFields: ['transcript', 'segments', 'language', 'duration', 'words'],
  },
  {
    id: 'cnvrt-ocr',
    provider: 'cnvrt.ing',
    baseUrl: 'https://cnvrt.ing',
    path: '/api/ocr',
    name: 'Image OCR',
    description: 'Extract text from images, PDFs, and scanned documents using advanced OCR with layout preservation.',
    category: 'media',
    costPerCall: 0.01,
    latencyMs: 2000,
    inputSchema: { fileUrl: 'URL of image or PDF', language: 'OCR language (default: auto)', preserveLayout: 'Maintain original formatting (default: true)' },
    outputFields: ['text', 'blocks', 'confidence', 'pages'],
  },

  // ─── didit (unified auth) ───────────────────────────────────────────────────

  {
    id: 'didit-auth',
    provider: 'didit',
    baseUrl: 'https://apx.didit.me',
    path: '/auth/token',
    name: 'Didit Unified Auth',
    description: 'Unified authentication supporting 100+ OAuth providers. Generate and validate tokens for any major auth provider.',
    category: 'infrastructure',
    costPerCall: 0.002,
    latencyMs: 400,
    inputSchema: { provider: 'OAuth provider (google, github, twitter, etc.)', code: 'OAuth authorization code' },
    outputFields: ['accessToken', 'refreshToken', 'expiresIn', 'userInfo', 'provider'],
  },

  // ─── TextBelt (SMS) ─────────────────────────────────────────────────────────

  {
    id: 'textbelt-sms',
    provider: 'TextBelt',
    baseUrl: 'https://textbelt.com',
    path: '/text',
    name: 'TextBelt SMS',
    description: 'Send SMS messages programmatically via TextBelt. No account setup required. Global coverage.',
    category: 'infrastructure',
    costPerCall: 0.01,
    latencyMs: 1000,
    inputSchema: { phone: 'Recipient phone number (E.164 format)', message: 'SMS message text (max 160 chars)' },
    outputFields: ['success', 'textId', 'quotaRemaining'],
  },

  // ─── Chronos (timezone) ─────────────────────────────────────────────────────

  {
    id: 'chronos-time',
    provider: 'Chronos',
    baseUrl: 'https://api.chronos.dev',
    path: '/current',
    name: 'Chronos Current Time',
    description: 'Get current time for any IANA timezone. Includes UTC offset, DST status, and locale-formatted time.',
    category: 'utility',
    costPerCall: 0.0005,
    latencyMs: 100,
    inputSchema: { timezone: 'IANA timezone (e.g. America/New_York)', format: 'Output format (iso | unix | human, default: iso)' },
    outputFields: ['datetime', 'timezone', 'utcOffset', 'isDST', 'unixTimestamp'],
  },
  {
    id: 'chronos-convert',
    provider: 'Chronos',
    baseUrl: 'https://api.chronos.dev',
    path: '/convert',
    name: 'Chronos Timezone Convert',
    description: 'Convert a datetime from one IANA timezone to another with DST handling.',
    category: 'utility',
    costPerCall: 0.0005,
    latencyMs: 100,
    inputSchema: { datetime: 'ISO 8601 datetime string', from: 'Source IANA timezone', to: 'Target IANA timezone' },
    outputFields: ['converted', 'fromTimezone', 'toTimezone', 'utcOffset'],
  },

  // ─── AgentMail (email for AI agents) ───────────────────────────────────────

  {
    id: 'agentmail-send',
    provider: 'AgentMail',
    baseUrl: 'https://api.agentmail.to',
    path: '/v1/send',
    name: 'AgentMail Send',
    description: 'Send transactional emails from AI agents programmatically. Supports HTML, attachments, and threading.',
    category: 'infrastructure',
    costPerCall: 0.002,
    latencyMs: 500,
    inputSchema: { to: 'Recipient email address', subject: 'Email subject', body: 'Email body (HTML or plain text)', from: 'Sender name (optional)' },
    outputFields: ['messageId', 'status', 'timestamp'],
  },
  {
    id: 'agentmail-inbox',
    provider: 'AgentMail',
    baseUrl: 'https://api.agentmail.to',
    path: '/v1/inbox',
    name: 'AgentMail Inbox',
    description: 'Create and manage programmatic email inboxes for AI agents. Read received emails, manage threads.',
    category: 'infrastructure',
    costPerCall: 0.001,
    latencyMs: 300,
    inputSchema: { action: 'create | list | read', inboxId: 'Inbox ID (for read/list actions)' },
    outputFields: ['inbox', 'messages', 'threads', 'unreadCount'],
  },

  // ─── Agoragentic (agent-to-agent marketplace) ──────────────────────────────

  {
    id: 'agoragentic-discover',
    provider: 'Agoragentic',
    baseUrl: 'https://agoragentic.com',
    path: '/api/capabilities',
    name: 'Agoragentic Discover',
    description: 'Discover agent capabilities on the Agoragentic agent-to-agent marketplace. Browse and search 26+ endpoints by category.',
    category: 'discovery',
    costPerCall: 0.002,
    latencyMs: 400,
    inputSchema: { category: 'Filter by category (optional)', query: 'Search query (optional)', limit: 'Max results (default 20)' },
    outputFields: ['capabilities', 'totalCount', 'categories'],
  },
  {
    id: 'agoragentic-invoke',
    provider: 'Agoragentic',
    baseUrl: 'https://agoragentic.com',
    path: '/api/invoke',
    name: 'Agoragentic Invoke',
    description: 'Invoke any agent capability on the Agoragentic marketplace. Autonomous agent-to-agent task delegation with USDC payment.',
    category: 'ai-ml',
    costPerCall: 0.01,
    latencyMs: 2000,
    inputSchema: { capabilityId: 'Capability ID from discovery', inputs: 'JSON inputs for the capability' },
    outputFields: ['result', 'cost', 'latency', 'agentId'],
  },

  // ─── Web Search providers ───────────────────────────────────────────────────

  {
    id: 'jina-search',
    provider: 'Jina AI',
    baseUrl: 'https://s.jina.ai',
    path: '/',
    name: 'Jina Web Search',
    description: 'Fast multilingual web search returning clean, LLM-ready results. Supports 100+ languages. No JS overhead.',
    category: 'search',
    costPerCall: 0.005,
    latencyMs: 800,
    inputSchema: { query: 'Search query', limit: 'Max results (default 10)', lang: 'Language code (default: en)' },
    outputFields: ['results', 'title', 'url', 'snippet', 'publishedDate'],
  },
  {
    id: 'perplexity-search',
    provider: 'Perplexity',
    baseUrl: 'https://api.perplexity.ai',
    path: '/chat/completions',
    name: 'Perplexity AI Search',
    description: 'AI-powered web search with citations and deep research capabilities. Returns synthesized answers with sources.',
    category: 'search',
    costPerCall: 0.06,
    latencyMs: 3000,
    inputSchema: { query: 'Search query or research question', model: 'sonar | sonar-pro | sonar-deep-research (default: sonar)', recencyFilter: 'day | week | month | year (optional)' },
    outputFields: ['answer', 'citations', 'sources', 'searchQuality'],
  },
  {
    id: 'tavily-search',
    provider: 'Tavily',
    baseUrl: 'https://api.tavily.com',
    path: '/search',
    name: 'Tavily Search',
    description: 'Real-time AI-optimized web search. Returns structured results with relevance scores, perfect for RAG pipelines.',
    category: 'search',
    costPerCall: 0.01,
    latencyMs: 1500,
    inputSchema: { query: 'Search query', searchDepth: 'basic | advanced (default: basic)', maxResults: 'Max results (default 5)', includeDomains: 'Comma-separated domains to include', excludeDomains: 'Comma-separated domains to exclude' },
    outputFields: ['results', 'answer', 'query', 'responseTime'],
  },
  {
    id: 'tavily-crawl',
    provider: 'Tavily',
    baseUrl: 'https://api.tavily.com',
    path: '/crawl',
    name: 'Tavily Crawl',
    description: 'Crawl and extract content from a URL as clean text for LLM processing. Handles dynamic sites.',
    category: 'scraping',
    costPerCall: 0.005,
    latencyMs: 2000,
    inputSchema: { url: 'URL to crawl', maxDepth: 'Crawl depth (default 1)', limit: 'Max pages (default 10)' },
    outputFields: ['pages', 'content', 'links', 'metadata'],
  },
  {
    id: 'searchapi-serp',
    provider: 'SearchAPI',
    baseUrl: 'https://www.searchapi.io',
    path: '/api/v1/search',
    name: 'SearchAPI SERP',
    description: 'Real-time SERP data from Google, YouTube, Amazon, Bing, eBay, and 100+ platforms. Structured search results.',
    category: 'search',
    costPerCall: 0.01,
    latencyMs: 1500,
    inputSchema: { q: 'Search query', engine: 'google | youtube | amazon | bing (default: google)', num: 'Results per page (default 10)', location: 'Location for geo-targeted results' },
    outputFields: ['organicResults', 'paidResults', 'knowledgeGraph', 'relatedSearches', 'totalResults'],
  },
  {
    id: 'sybil-search',
    provider: 'Sybil',
    baseUrl: 'https://api.sybil.com',
    path: '/search',
    name: 'Sybil Unified Search',
    description: 'Combined web search using Exa + xAI Grok for comprehensive results. Best-in-class recall for AI agents.',
    category: 'search',
    costPerCall: 0.02,
    latencyMs: 2000,
    inputSchema: { query: 'Search query', mode: 'web | neural | combined (default: combined)', numResults: 'Results to return (default 10)' },
    outputFields: ['results', 'url', 'title', 'content', 'score', 'publishedDate'],
  },
  {
    id: 'parallel-research',
    provider: 'Parallel',
    baseUrl: 'https://api.parallel.ai',
    path: '/v1/research',
    name: 'Parallel Web Research',
    description: 'Deep web research and content extraction for AI agents. FindAll entity discovery mode surfaces comprehensive data.',
    category: 'search',
    costPerCall: 0.02,
    latencyMs: 3000,
    inputSchema: { query: 'Research query', mode: 'search | research | findall (default: research)', depth: 'Depth of research (1-5, default 2)' },
    outputFields: ['answer', 'sources', 'entities', 'facts', 'confidence'],
  },
  {
    id: 'valyu-search',
    provider: 'Valyu',
    baseUrl: 'https://api.valyu.network',
    path: '/v1/search',
    name: 'Valyu AI Search',
    description: 'AI-powered search combining public web and proprietary data sources for research-grade results.',
    category: 'search',
    costPerCall: 0.015,
    latencyMs: 2000,
    inputSchema: { query: 'Search query', dataSources: 'web | proprietary | all (default: all)', maxResults: 'Max results (default 10)' },
    outputFields: ['results', 'answer', 'sources', 'proprietaryData'],
  },

  // ─── Additional Web Scrapers ────────────────────────────────────────────────

  {
    id: 'zyte-scrape',
    provider: 'Zyte',
    baseUrl: 'https://api.zyte.com/v1',
    path: '/extract',
    name: 'Zyte Smart Extraction',
    description: 'Anti-bot bypass web scraping with AI extraction. Handles JavaScript rendering, CAPTCHAs, and complex SPAs.',
    category: 'scraping',
    costPerCall: 0.01,
    latencyMs: 3000,
    inputSchema: { url: 'URL to scrape', articleBodyHtml: 'Extract article body (true/false)', product: 'Extract product data (true/false)', browserHtml: 'Return full rendered HTML (true/false)' },
    outputFields: ['articleBody', 'product', 'html', 'screenshot', 'httpResponseBody'],
  },
  {
    id: 'notte-extract',
    provider: 'Notte',
    baseUrl: 'https://api.notte.cc',
    path: '/extract',
    name: 'Notte AI Extraction',
    description: 'AI content extraction from web pages, PDFs, and documents. Returns structured data from unstructured sources.',
    category: 'scraping',
    costPerCall: 0.008,
    latencyMs: 2000,
    inputSchema: { source: 'URL or base64 document', schema: 'JSON schema for structured output (optional)', extractionType: 'text | table | structured (default: text)' },
    outputFields: ['content', 'structured', 'tables', 'metadata'],
  },
  {
    id: 'scrapegraph-extract',
    provider: 'ScrapeGraph',
    baseUrl: 'https://api.scrapegraph.ai',
    path: '/v1/smartscraper',
    name: 'ScrapeGraph Smart Scraper',
    description: 'AI-powered web scraping that understands page context. Describe what you want and get structured data back.',
    category: 'scraping',
    costPerCall: 0.01,
    latencyMs: 3000,
    inputSchema: { website_url: 'URL to scrape', user_prompt: 'Describe what data to extract', output_schema: 'Optional JSON schema for output' },
    outputFields: ['result', 'status', 'requestId'],
  },
  {
    id: 'fiber-scrape',
    provider: 'Fiber',
    baseUrl: 'https://api.fiber.dev',
    path: '/v1/scrape',
    name: 'Fiber Scrape',
    description: 'Web scraping with built-in proxy rotation, JavaScript rendering, and AI data extraction. High throughput.',
    category: 'scraping',
    costPerCall: 0.005,
    latencyMs: 2000,
    inputSchema: { url: 'URL to scrape', renderJs: 'Enable JS rendering (default: true)', extract: 'AI extraction prompt (optional)', proxy: 'Proxy type: residential | datacenter (default: residential)' },
    outputFields: ['html', 'text', 'extracted', 'statusCode', 'headers'],
  },

  // ─── Social Media providers ─────────────────────────────────────────────────

  {
    id: 'neynar-search',
    provider: 'Neynar',
    baseUrl: 'https://hub-api.neynar.com',
    path: '/v1/castsByMention',
    name: 'Neynar Farcaster Search',
    description: 'Search Farcaster casts, user profiles, channels, and feeds. The leading Farcaster data API.',
    category: 'social',
    costPerCall: 0.005,
    latencyMs: 400,
    inputSchema: { query: 'Search term or topic', limit: 'Max results (default 25)', channel: 'Filter by Farcaster channel (optional)' },
    outputFields: ['casts', 'users', 'channels', 'reactions'],
  },
  {
    id: 'neynar-profile',
    provider: 'Neynar',
    baseUrl: 'https://hub-api.neynar.com',
    path: '/v1/userByUsername',
    name: 'Neynar Farcaster Profile',
    description: 'Fetch a Farcaster user profile: follower count, following, casts, and on-chain verifications.',
    category: 'social',
    costPerCall: 0.003,
    latencyMs: 300,
    inputSchema: { username: 'Farcaster username (without @)', fid: 'Farcaster FID (alternative to username)' },
    outputFields: ['fid', 'username', 'displayName', 'bio', 'followerCount', 'followingCount', 'verifications'],
  },
  {
    id: 'reddit-search',
    provider: 'Reddit',
    baseUrl: 'https://api.reddit.com',
    path: '/search.json',
    name: 'Reddit Search',
    description: 'Search Reddit posts, comments, and communities. Includes sentiment, upvotes, and engagement metrics.',
    category: 'social',
    costPerCall: 0.002,
    latencyMs: 500,
    inputSchema: { q: 'Search query', subreddit: 'Limit to subreddit (optional)', sort: 'hot | new | top | relevance (default: relevance)', limit: 'Max posts (default 25)', time: 'hour | day | week | month | year | all' },
    outputFields: ['posts', 'title', 'score', 'comments', 'url', 'subreddit', 'created'],
  },
  {
    id: 'scrape-creators',
    provider: 'ScrapeCreators',
    baseUrl: 'https://api.scrapecreators.com',
    path: '/v1/search',
    name: 'ScrapeCreators Social',
    description: 'Extract social media data from 22+ platforms: TikTok, Instagram, YouTube, Twitter/X, LinkedIn, Snapchat, and more.',
    category: 'social',
    costPerCall: 0.008,
    latencyMs: 1500,
    inputSchema: { platform: 'tiktok | instagram | youtube | twitter | linkedin', type: 'profile | posts | search | comments', identifier: 'Username, hashtag, or query', limit: 'Max results (default 20)' },
    outputFields: ['posts', 'profile', 'metrics', 'platform', 'timestamp'],
  },

  // ─── Blockchain / DeFi (new providers) ─────────────────────────────────────

  {
    id: 'nansen-smartmoney',
    provider: 'Nansen',
    baseUrl: 'https://api.nansen.ai',
    path: '/v2/smart-money/wallets',
    name: 'Nansen Smart Money',
    description: 'Smart money analytics from Nansen: whale tracking, labeled wallet activity, token net flows, and DEX trades by institutional wallets.',
    category: 'intelligence',
    costPerCall: 0.02,
    latencyMs: 1000,
    inputSchema: { token: 'Token address or symbol', chain: 'ethereum | solana | base | polygon (default: ethereum)', timeframe: '1d | 7d | 30d (default: 7d)' },
    outputFields: ['smartMoneyBuying', 'smartMoneySelling', 'netFlow', 'topWallets', 'walletLabels'],
  },
  {
    id: 'zapper-portfolio',
    provider: 'Zapper',
    baseUrl: 'https://api.zapper.xyz',
    path: '/v2/balances',
    name: 'Zapper Portfolio',
    description: 'Portfolio balances, DeFi positions, NFT holdings, and token prices across 60+ chains. Aggregated net worth.',
    category: 'defi',
    costPerCall: 0.01,
    latencyMs: 1500,
    inputSchema: { address: 'Wallet address (EVM or ENS)', networks: 'Comma-separated chains (default: all)', groupBy: 'wallet | protocol (default: wallet)' },
    outputFields: ['netWorth', 'tokens', 'defiPositions', 'nfts', 'chains'],
  },
  {
    id: 'silverback-ta',
    provider: 'Silverback',
    baseUrl: 'https://api.silverback.finance',
    path: '/v1/analysis',
    name: 'Silverback Technical Analysis',
    description: 'Advanced technical analysis, arbitrage scanning, DeFi yield discovery, and whale monitoring for any crypto asset.',
    category: 'intelligence',
    costPerCall: 0.015,
    latencyMs: 1200,
    inputSchema: { symbol: 'Asset symbol or contract address', chain: 'Blockchain (default: solana)', type: 'ta | arbitrage | yield | whales (default: ta)' },
    outputFields: ['signals', 'indicators', 'arbitrageOpportunities', 'yieldRates', 'whaleActivity'],
  },
  {
    id: 'blocksec-risk',
    provider: 'BlockSec',
    baseUrl: 'https://api.blocksec.com',
    path: '/v1/aml/screen',
    name: 'BlockSec AML Screen',
    description: 'Address compliance screening and AML risk assessment. Know Your Address (KYA) reports for regulatory compliance.',
    category: 'security',
    costPerCall: 0.05,
    latencyMs: 1000,
    inputSchema: { address: 'Wallet address to screen', chain: 'Blockchain (ethereum | solana | bsc | polygon)', level: 'basic | standard | comprehensive (default: standard)' },
    outputFields: ['riskScore', 'riskLevel', 'flags', 'sanctions', 'exposure', 'labels', 'report'],
  },
  {
    id: 'ordiscan-inscriptions',
    provider: 'Ordiscan',
    baseUrl: 'https://api.ordiscan.com',
    path: '/v1/inscriptions',
    name: 'Ordiscan Inscriptions',
    description: 'Bitcoin Ordinals inscription data: metadata, content, ownership, transfers, and rarity scores.',
    category: 'defi',
    costPerCall: 0.005,
    latencyMs: 500,
    inputSchema: { id: 'Inscription ID or number', address: 'Bitcoin address to list inscriptions for (alternative)' },
    outputFields: ['inscriptionId', 'number', 'contentType', 'content', 'owner', 'genesisBlock', 'sat'],
  },
  {
    id: 'ordiscan-runes',
    provider: 'Ordiscan',
    baseUrl: 'https://api.ordiscan.com',
    path: '/v1/runes/balances',
    name: 'Ordiscan Runes',
    description: 'Bitcoin Runes protocol balances, BRC-20 token holdings, rare sat data, and UTXO information.',
    category: 'defi',
    costPerCall: 0.005,
    latencyMs: 500,
    inputSchema: { address: 'Bitcoin address', type: 'runes | brc20 | sats (default: runes)' },
    outputFields: ['runes', 'brc20', 'rareSats', 'utxos', 'totalValue'],
  },
  {
    id: 'dome-markets',
    provider: 'Dome',
    baseUrl: 'https://api.dome.fi',
    path: '/v1/markets',
    name: 'Dome Prediction Markets',
    description: 'Prediction market data from Polymarket, Kalshi, sports markets. Live odds, volume, and resolution data.',
    category: 'oracle',
    costPerCall: 0.005,
    latencyMs: 400,
    inputSchema: { query: 'Market search query', platform: 'polymarket | kalshi | all (default: all)', status: 'open | closed | all (default: open)', category: 'politics | crypto | sports | science (optional)' },
    outputFields: ['markets', 'title', 'probability', 'volume', 'resolves', 'outcomes'],
  },
  {
    id: 'spraay-defi',
    provider: 'Spraay',
    baseUrl: 'https://api.spraay.io',
    path: '/v1/defi',
    name: 'Spraay DeFi Infrastructure',
    description: 'Full-stack DeFi infrastructure: token swaps, price oracles, cross-chain bridges, payroll, escrow, and AI inference (Claude/GPT) via single API.',
    category: 'defi',
    costPerCall: 0.01,
    latencyMs: 800,
    inputSchema: { action: 'swap | oracle | bridge | escrow | inference', params: 'Action-specific parameters as JSON', chain: 'solana | base | ethereum (default: solana)' },
    outputFields: ['result', 'txHash', 'cost', 'latency', 'action'],
  },

  // ─── Image / Audio / Video ──────────────────────────────────────────────────

  {
    id: 'x402engine-image-fast',
    provider: 'x402engine',
    baseUrl: 'https://x402-gateway-production.up.railway.app',
    path: '/api/image/fast',
    name: 'x402engine Fast Image',
    description: 'Fast AI image generation with FLUX Schnell. $0.015/image. Best for high-volume or draft quality.',
    category: 'media',
    costPerCall: 0.015,
    latencyMs: 3000,
    inputSchema: { prompt: 'Image generation prompt', width: 'Width in pixels (default 1024)', height: 'Height in pixels (default 1024)', steps: 'Diffusion steps (default 4)' },
    outputFields: ['imageUrl', 'seed', 'width', 'height', 'model'],
  },
  {
    id: 'x402engine-image-quality',
    provider: 'x402engine',
    baseUrl: 'https://x402-gateway-production.up.railway.app',
    path: '/api/image/quality',
    name: 'x402engine Quality Image',
    description: 'High-quality AI image generation with FLUX.2 Pro. $0.05/image. Best for production use.',
    category: 'media',
    costPerCall: 0.05,
    latencyMs: 6000,
    inputSchema: { prompt: 'Image generation prompt', width: 'Width (default 1024)', height: 'Height (default 1024)', guidance: 'CFG scale (default 3.5)' },
    outputFields: ['imageUrl', 'seed', 'width', 'height', 'model'],
  },
  {
    id: 'x402engine-image-text',
    provider: 'x402engine',
    baseUrl: 'https://x402-gateway-production.up.railway.app',
    path: '/api/image/text',
    name: 'x402engine Text-in-Image',
    description: 'Generate images with accurate text rendering using Ideogram v3. $0.12/image. Great for logos, banners, posters.',
    category: 'media',
    costPerCall: 0.12,
    latencyMs: 8000,
    inputSchema: { prompt: 'Image prompt with text to render', style: 'auto | design | realistic | anime (default: auto)', aspectRatio: '1:1 | 16:9 | 9:16 | 4:3 (default: 1:1)' },
    outputFields: ['imageUrl', 'seed', 'style', 'model'],
  },
  {
    id: 'x402engine-tts',
    provider: 'x402engine',
    baseUrl: 'https://x402-gateway-production.up.railway.app',
    path: '/api/tts/openai',
    name: 'x402engine TTS',
    description: 'Text-to-speech audio generation via OpenAI TTS. $0.01/request. Natural voices, multiple languages.',
    category: 'media',
    costPerCall: 0.01,
    latencyMs: 2000,
    inputSchema: { text: 'Text to convert to speech (max 4096 chars)', voice: 'alloy | echo | fable | onyx | nova | shimmer (default: nova)', speed: 'Speed 0.25-4.0 (default 1.0)' },
    outputFields: ['audioUrl', 'duration', 'voice', 'format'],
  },
  {
    id: 'x402engine-transcribe',
    provider: 'x402engine',
    baseUrl: 'https://x402-gateway-production.up.railway.app',
    path: '/api/transcribe',
    name: 'x402engine Transcribe',
    description: 'Audio transcription via Deepgram Nova-3. $0.10/request. 99%+ accuracy, speaker detection, timestamps.',
    category: 'media',
    costPerCall: 0.10,
    latencyMs: 4000,
    inputSchema: { audioUrl: 'URL of audio file to transcribe', language: 'Language code (default: en)', diarize: 'Speaker diarization (default: false)' },
    outputFields: ['transcript', 'words', 'speakers', 'confidence', 'duration'],
  },
  {
    id: 'dtelecom-stt',
    provider: 'dTelecom',
    baseUrl: 'https://api.dtelecom.org',
    path: '/v1/asr',
    name: 'dTelecom Speech-to-Text',
    description: 'Real-time speech-to-text with dual-engine architecture (Whisper + Conformer). 99+ languages, streaming support.',
    category: 'media',
    costPerCall: 0.015,
    latencyMs: 3000,
    inputSchema: { audioUrl: 'URL of audio file or stream', language: 'Language code or auto (default: auto)', model: 'whisper | conformer | auto (default: auto)', stream: 'Enable streaming transcription (default: false)' },
    outputFields: ['transcript', 'language', 'confidence', 'words', 'duration', 'model'],
  },
  {
    id: 'aibeats-music',
    provider: 'AIBeats',
    baseUrl: 'https://api.aibeats.xyz',
    path: '/v1/generate',
    name: 'AIBeats Music Generation',
    description: 'AI music generation from text prompts. Create original tracks, beats, and instrumentals in any genre.',
    category: 'media',
    costPerCall: 0.05,
    latencyMs: 10000,
    inputSchema: { prompt: 'Music generation prompt (genre, mood, instruments)', duration: 'Duration in seconds (default 30, max 120)', style: 'Genre/style tag (optional)' },
    outputFields: ['audioUrl', 'duration', 'genre', 'bpm', 'key'],
  },
  {
    id: 'genbase-video',
    provider: 'Genbase',
    baseUrl: 'https://api.genbase.ai',
    path: '/v1/generate',
    name: 'Genbase Video Generation',
    description: 'AI video generation with Sora 2, xAI Grok Imagine, and GPT Image. Create videos from text prompts.',
    category: 'media',
    costPerCall: 0.50,
    latencyMs: 30000,
    inputSchema: { prompt: 'Video generation prompt', model: 'sora | grok | gpt-image (default: sora)', duration: 'Duration in seconds (default 5)', resolution: '720p | 1080p (default: 720p)' },
    outputFields: ['videoUrl', 'duration', 'resolution', 'model', 'frames'],
  },
  {
    id: 'freepik-image',
    provider: 'Freepik',
    baseUrl: 'https://api.freepik.com',
    path: '/v1/ai/mystic',
    name: 'Freepik Mystic Image',
    description: 'AI image generation with Freepik Mystic. High-quality outputs in multiple styles: photorealistic, artistic, digital art.',
    category: 'media',
    costPerCall: 0.04,
    latencyMs: 5000,
    inputSchema: { prompt: 'Image generation prompt', style: 'photorealistic | digital-art | anime | watercolor', aspectRatio: '1:1 | 16:9 | 9:16 | 4:3 (default: 1:1)', guidance: 'CFG scale 1-10 (default 7)' },
    outputFields: ['imageUrl', 'seed', 'style', 'width', 'height'],
  },
  {
    id: 'bittensor-inference',
    provider: 'Bittensor',
    baseUrl: 'https://api.bittensor.com',
    path: '/v1/inference',
    name: 'Bittensor AI Inference',
    description: 'Access 13 Bittensor AI subnets through a single endpoint: text, image, video, 3D, translation, time-series, voice.',
    category: 'ai-ml',
    costPerCall: 0.02,
    latencyMs: 3000,
    inputSchema: { subnet: 'Subnet ID (1-13) or type: text | image | video | 3d | translation | forecast | voice', prompt: 'Input prompt or data', model: 'Specific model within subnet (optional)' },
    outputFields: ['result', 'subnet', 'model', 'processingTime', 'credits'],
  },
  {
    id: 'quiver-svg',
    provider: 'QuiverAI',
    baseUrl: 'https://api.quiver.ai',
    path: '/v1/svg',
    name: 'Quiver SVG Generation',
    description: 'AI SVG generation from text prompts and raster image vectorization. Clean, scalable vector output.',
    category: 'media',
    costPerCall: 0.03,
    latencyMs: 4000,
    inputSchema: { prompt: 'SVG generation prompt', imageUrl: 'Raster image to vectorize (alternative to prompt)', style: 'minimal | detailed | icon | illustration (default: minimal)' },
    outputFields: ['svgContent', 'svgUrl', 'width', 'height', 'elements'],
  },
  {
    id: 'tavus-video',
    provider: 'Tavus',
    baseUrl: 'https://tavusapi.com',
    path: '/v2/videos',
    name: 'Tavus AI Video',
    description: 'AI-powered personalized video generation with realistic digital twin avatars and conversational video interfaces.',
    category: 'media',
    costPerCall: 0.25,
    latencyMs: 20000,
    inputSchema: { script: 'Video script text', replicaId: 'Digital twin ID (optional)', background: 'Background URL or color (optional)', voiceId: 'Voice ID for audio (optional)' },
    outputFields: ['videoId', 'videoUrl', 'duration', 'status', 'replicaId'],
  },

  // ─── Security & Risk ────────────────────────────────────────────────────────

  {
    id: 'orac-inject-scan',
    provider: 'Orac',
    baseUrl: 'https://api.orac.ai',
    path: '/v1/scan/prompt',
    name: 'Orac Prompt Injection Scan',
    description: 'Detect prompt injection attacks and jailbreak attempts in user inputs before they reach your LLM.',
    category: 'security',
    costPerCall: 0.005,
    latencyMs: 300,
    inputSchema: { prompt: 'User input to scan', threshold: 'Sensitivity 0-1 (default 0.8)', context: 'System prompt context for better detection (optional)' },
    outputFields: ['isInjection', 'confidence', 'attackType', 'sanitized', 'explanation'],
  },
  {
    id: 'orac-code-audit',
    provider: 'Orac',
    baseUrl: 'https://api.orac.ai',
    path: '/v1/audit/code',
    name: 'Orac Code Vulnerability Audit',
    description: 'AI-powered code security audit. Detects OWASP Top 10, injection flaws, insecure deps, and logic vulnerabilities.',
    category: 'security',
    costPerCall: 0.02,
    latencyMs: 2000,
    inputSchema: { code: 'Source code to audit', language: 'Programming language (auto-detected if omitted)', severity: 'critical | high | all (default: all)' },
    outputFields: ['vulnerabilities', 'severity', 'line', 'description', 'fix', 'cveIds'],
  },
  {
    id: 'actiongate-score',
    provider: 'ActionGate',
    baseUrl: 'https://api.actiongate.ai',
    path: '/v1/agent/score',
    name: 'ActionGate Agent Risk Score',
    description: 'Real-time risk scoring for AI agent actions. Flags malicious intent, policy violations, and unsafe operations.',
    category: 'security',
    costPerCall: 0.015,
    latencyMs: 400,
    inputSchema: { action: 'Agent action description or code', context: 'Agent system prompt and history (optional)', threshold: 'Risk threshold 0-1 (default 0.7)' },
    outputFields: ['riskScore', 'riskLevel', 'flags', 'recommendation', 'blocked'],
  },
  {
    id: 'kevros-governance',
    provider: 'Kevros',
    baseUrl: 'https://api.kevros.ai',
    path: '/v1/governance/check',
    name: 'Kevros AI Governance',
    description: 'AI governance and compliance check. Verify AI outputs against regulatory frameworks (EU AI Act, NIST, ISO 42001).',
    category: 'security',
    costPerCall: 0.05,
    latencyMs: 800,
    inputSchema: { content: 'AI output or action to evaluate', framework: 'eu-ai-act | nist | iso42001 | all (default: all)', useCase: 'Deployment context description' },
    outputFields: ['compliant', 'violations', 'riskLevel', 'framework', 'recommendations', 'score'],
  },

  // ─── Lead Enrichment ────────────────────────────────────────────────────────

  {
    id: 'apollo-search',
    provider: 'Apollo',
    baseUrl: 'https://api.apollo.io',
    path: '/v1/people/search',
    name: 'Apollo People Search',
    description: 'Search 270M+ contacts database. Find people by job title, company, industry, and location with verified email.',
    category: 'enrichment',
    costPerCall: 0.02,
    latencyMs: 800,
    inputSchema: { name: 'Person name (optional)', company: 'Company name or domain (optional)', title: 'Job title keyword', location: 'City, state, or country (optional)', limit: 'Results per page (default 10)' },
    outputFields: ['people', 'name', 'title', 'company', 'email', 'linkedin', 'phone', 'location'],
  },
  {
    id: 'apollo-company',
    provider: 'Apollo',
    baseUrl: 'https://api.apollo.io',
    path: '/v1/organizations/search',
    name: 'Apollo Company Enrichment',
    description: 'Enrich company data from Apollo: employee count, revenue, tech stack, funding, and key contacts.',
    category: 'enrichment',
    costPerCall: 0.015,
    latencyMs: 600,
    inputSchema: { domain: 'Company website domain', name: 'Company name (alternative to domain)' },
    outputFields: ['name', 'domain', 'industry', 'employees', 'revenue', 'funding', 'technologies', 'contacts'],
  },
  {
    id: 'hunter-email-find',
    provider: 'Hunter',
    baseUrl: 'https://api.hunter.io',
    path: '/v2/email-finder',
    name: 'Hunter Email Finder',
    description: 'Find verified email addresses for any professional by name and company domain.',
    category: 'enrichment',
    costPerCall: 0.01,
    latencyMs: 500,
    inputSchema: { domain: 'Company domain (e.g. company.com)', first_name: 'First name', last_name: 'Last name' },
    outputFields: ['email', 'score', 'firstName', 'lastName', 'position', 'confidence'],
  },
  {
    id: 'hunter-domain-search',
    provider: 'Hunter',
    baseUrl: 'https://api.hunter.io',
    path: '/v2/domain-search',
    name: 'Hunter Domain Search',
    description: 'Find all email addresses and employee contacts at a company by domain. Includes email patterns.',
    category: 'enrichment',
    costPerCall: 0.015,
    latencyMs: 600,
    inputSchema: { domain: 'Company domain to search', limit: 'Max emails (default 10)', type: 'personal | generic | all (default: all)' },
    outputFields: ['emails', 'pattern', 'organization', 'disposable', 'webmail', 'totalEmails'],
  },
  {
    id: 'openmart-business',
    provider: 'OpenMart',
    baseUrl: 'https://api.openmart.ai',
    path: '/v1/businesses/search',
    name: 'OpenMart Business Search',
    description: 'Search and enrich 30M+ local businesses. Find leads by category, location, and size with contact details.',
    category: 'enrichment',
    costPerCall: 0.01,
    latencyMs: 700,
    inputSchema: { query: 'Business type or name', location: 'City, state, or zip code', radius: 'Search radius in miles (default 10)', limit: 'Max results (default 20)' },
    outputFields: ['businesses', 'name', 'address', 'phone', 'email', 'website', 'category', 'employees'],
  },
  {
    id: 'coresignal-company',
    provider: 'CoreSignal',
    baseUrl: 'https://api.coresignal.com',
    path: '/cdapi/v2/linkedin/company/search/filter',
    name: 'CoreSignal B2B Data',
    description: 'B2B company and employee data from CoreSignal. Employee directories, headcount changes, and recruitment signals.',
    category: 'enrichment',
    costPerCall: 0.02,
    latencyMs: 800,
    inputSchema: { name: 'Company name or domain', industry: 'Industry filter (optional)', size: 'Company size range (optional)', country: 'Country code (optional)' },
    outputFields: ['company', 'employees', 'headcount', 'openJobs', 'linkedinUrl', 'founded', 'specialties'],
  },
  {
    id: 'tomba-email',
    provider: 'Tomba',
    baseUrl: 'https://api.tomba.io',
    path: '/v1/domain-search',
    name: 'Tomba Email Discovery',
    description: 'Find and verify email addresses by company domain. Discover company tech stack and social profiles.',
    category: 'enrichment',
    costPerCall: 0.008,
    latencyMs: 500,
    inputSchema: { domain: 'Company domain (e.g. company.com)', limit: 'Max emails (default 10)' },
    outputFields: ['emails', 'pattern', 'organization', 'technologies', 'social', 'verification'],
  },
  {
    id: 'predictleads-intel',
    provider: 'PredictLeads',
    baseUrl: 'https://predictleads.com',
    path: '/api/v3/companies',
    name: 'PredictLeads Company Intel',
    description: 'Company intelligence signals: job openings, news events, financing rounds, technology detections, and growth indicators.',
    category: 'enrichment',
    costPerCall: 0.02,
    latencyMs: 700,
    inputSchema: { domain: 'Company domain', signals: 'jobs | news | funding | technologies | all (default: all)' },
    outputFields: ['jobOpenings', 'newsEvents', 'financingEvents', 'technologies', 'growthScore', 'signals'],
  },
  {
    id: 'logo-search',
    provider: 'Logo.dev',
    baseUrl: 'https://img.logo.dev',
    path: '/',
    name: 'Logo Search',
    description: 'Retrieve company logos by domain. High-resolution PNG/SVG logos for 100K+ companies.',
    category: 'enrichment',
    costPerCall: 0.001,
    latencyMs: 200,
    inputSchema: { domain: 'Company domain (e.g. apple.com)', size: 'Logo size in pixels (default 128)', format: 'png | svg (default: png)' },
    outputFields: ['logoUrl', 'domain', 'format', 'size'],
  },

  // ─── Weather ────────────────────────────────────────────────────────────────

  {
    id: 'precip-weather',
    provider: 'Precip',
    baseUrl: 'https://api.precip.earth',
    path: '/v1/current',
    name: 'Precip Hyperlocal Weather',
    description: 'Hyperlocal weather data with site-specific accuracy: rainfall, temperature, humidity, wind speed, and soil moisture.',
    category: 'weather',
    costPerCall: 0.002,
    latencyMs: 400,
    inputSchema: { lat: 'Latitude', lon: 'Longitude', fields: 'Fields to return: rain | temp | humidity | wind | soil | all (default: all)' },
    outputFields: ['temperature', 'humidity', 'rainfall', 'windSpeed', 'windDirection', 'soilMoisture', 'uvIndex', 'timestamp'],
  },
  {
    id: 'precip-forecast',
    provider: 'Precip',
    baseUrl: 'https://api.precip.earth',
    path: '/v1/forecast',
    name: 'Precip Weather Forecast',
    description: 'Site-specific weather forecasts up to 14 days. Includes precipitation probability, temperature range, and severe weather alerts.',
    category: 'weather',
    costPerCall: 0.005,
    latencyMs: 600,
    inputSchema: { lat: 'Latitude', lon: 'Longitude', days: 'Forecast days 1-14 (default 7)', interval: 'hourly | daily (default: daily)' },
    outputFields: ['forecast', 'temperature', 'precipitation', 'humidity', 'wind', 'alerts', 'confidence'],
  },

  // ─── x402engine LLM Proxy (top models) ─────────────────────────────────────

  {
    id: 'x402engine-gpt4o',
    provider: 'x402engine',
    baseUrl: 'https://x402-gateway-production.up.railway.app',
    path: '/api/llm/gpt-4o',
    name: 'GPT-4o via x402',
    description: 'OpenAI GPT-4o via x402 micropayments. No account required. $0.04/request. Full vision + function calling support.',
    category: 'ai-ml',
    costPerCall: 0.04,
    latencyMs: 3000,
    inputSchema: { prompt: 'User message or prompt', systemPrompt: 'System prompt (optional)', imageUrl: 'Image URL for vision (optional)', maxTokens: 'Max output tokens (default 1024)' },
    outputFields: ['content', 'model', 'usage', 'finishReason'],
  },
  {
    id: 'x402engine-sonnet',
    provider: 'x402engine',
    baseUrl: 'https://x402-gateway-production.up.railway.app',
    path: '/api/llm/claude-sonnet-4-6',
    name: 'Claude Sonnet 4.6 via x402',
    description: 'Anthropic Claude Sonnet 4.6 via x402 micropayments. $0.06/request. Extended thinking, vision, code generation.',
    category: 'ai-ml',
    costPerCall: 0.06,
    latencyMs: 3000,
    inputSchema: { prompt: 'User message or prompt', systemPrompt: 'System prompt (optional)', maxTokens: 'Max output tokens (default 1024)', thinking: 'Enable extended thinking (default: false)' },
    outputFields: ['content', 'model', 'usage', 'finishReason'],
  },
  {
    id: 'x402engine-gemini',
    provider: 'x402engine',
    baseUrl: 'https://x402-gateway-production.up.railway.app',
    path: '/api/llm/gemini-2-5-flash',
    name: 'Gemini 2.5 Flash via x402',
    description: 'Google Gemini 2.5 Flash via x402 micropayments. $0.009/request. Fast, multimodal, 1M context window.',
    category: 'ai-ml',
    costPerCall: 0.009,
    latencyMs: 1500,
    inputSchema: { prompt: 'User message or prompt', systemPrompt: 'System prompt (optional)', imageUrl: 'Image URL for vision (optional)', maxTokens: 'Max output tokens (default 1024)' },
    outputFields: ['content', 'model', 'usage', 'finishReason'],
  },
  {
    id: 'x402engine-deepseek',
    provider: 'x402engine',
    baseUrl: 'https://x402-gateway-production.up.railway.app',
    path: '/api/llm/deepseek-v3',
    name: 'DeepSeek V3 via x402',
    description: 'DeepSeek V3 via x402 micropayments. $0.005/request. Best cost-per-token, strong at code and reasoning.',
    category: 'ai-ml',
    costPerCall: 0.005,
    latencyMs: 2000,
    inputSchema: { prompt: 'User message or prompt', systemPrompt: 'System prompt (optional)', maxTokens: 'Max output tokens (default 1024)' },
    outputFields: ['content', 'model', 'usage', 'finishReason'],
  },
  {
    id: 'x402engine-grok',
    provider: 'x402engine',
    baseUrl: 'https://x402-gateway-production.up.railway.app',
    path: '/api/llm/grok-4',
    name: 'Grok 4 via x402',
    description: 'xAI Grok 4 via x402 micropayments. $0.06/request. Real-time web search built-in, strong at current events.',
    category: 'ai-ml',
    costPerCall: 0.06,
    latencyMs: 3000,
    inputSchema: { prompt: 'User message or prompt', systemPrompt: 'System prompt (optional)', webSearch: 'Enable real-time web search (default: false)', maxTokens: 'Max output tokens (default 1024)' },
    outputFields: ['content', 'model', 'usage', 'sources', 'finishReason'],
  },
  {
    id: 'x402engine-embeddings',
    provider: 'x402engine',
    baseUrl: 'https://x402-gateway-production.up.railway.app',
    path: '/api/embeddings',
    name: 'x402engine Embeddings',
    description: 'Text embedding generation via x402. $0.001/request. OpenAI-compatible embedding format for RAG and semantic search.',
    category: 'ai-ml',
    costPerCall: 0.001,
    latencyMs: 500,
    inputSchema: { input: 'Text or array of texts to embed', model: 'Embedding model (default: text-embedding-3-small)', dimensions: 'Vector dimensions (optional)' },
    outputFields: ['embeddings', 'dimensions', 'model', 'usage'],
  },
  {
    id: 'x402engine-code-run',
    provider: 'x402engine',
    baseUrl: 'https://x402-gateway-production.up.railway.app',
    path: '/api/code/run',
    name: 'x402engine Code Sandbox',
    description: 'Execute code in a sandboxed environment via x402. Supports Python, JS, TS. $0.005/run. Safe, isolated execution.',
    category: 'ai-ml',
    costPerCall: 0.005,
    latencyMs: 3000,
    inputSchema: { code: 'Code to execute', language: 'python | javascript | typescript (default: python)', timeout: 'Execution timeout in seconds (default 30)', packages: 'Comma-separated packages to install (optional)' },
    outputFields: ['stdout', 'stderr', 'exitCode', 'duration', 'files'],
  },

  // ─── x402engine Web + Travel ────────────────────────────────────────────────

  {
    id: 'x402engine-scrape',
    provider: 'x402engine',
    baseUrl: 'https://x402-gateway-production.up.railway.app',
    path: '/api/web/scrape',
    name: 'x402engine Web Scrape',
    description: 'Web scraping via x402. Returns clean text content from any URL. $0.005/request.',
    category: 'scraping',
    costPerCall: 0.005,
    latencyMs: 2000,
    inputSchema: { url: 'URL to scrape', format: 'text | html | markdown (default: markdown)' },
    outputFields: ['content', 'title', 'url', 'statusCode'],
  },
  {
    id: 'x402engine-web-search',
    provider: 'x402engine',
    baseUrl: 'https://x402-gateway-production.up.railway.app',
    path: '/api/search/web',
    name: 'x402engine Web Search',
    description: 'Web search via x402 micropayments. Returns ranked results with snippets. $0.01/request.',
    category: 'search',
    costPerCall: 0.01,
    latencyMs: 1500,
    inputSchema: { query: 'Search query', num: 'Number of results (default 10)', lang: 'Language code (default: en)' },
    outputFields: ['results', 'title', 'url', 'snippet', 'position'],
  },
  {
    id: 'x402engine-flights',
    provider: 'x402engine',
    baseUrl: 'https://x402-gateway-production.up.railway.app',
    path: '/api/travel/flights',
    name: 'x402engine Flight Search',
    description: 'Real-time flight search via x402. Find available flights, prices, and schedules. $0.02/request.',
    category: 'utility',
    costPerCall: 0.02,
    latencyMs: 3000,
    inputSchema: { origin: 'Origin airport IATA code', destination: 'Destination airport IATA code', date: 'Departure date (YYYY-MM-DD)', adults: 'Number of adult passengers (default 1)', cabinClass: 'economy | business | first (default: economy)' },
    outputFields: ['flights', 'price', 'airline', 'departure', 'arrival', 'duration', 'stops'],
  },
  {
    id: 'x402engine-hotels',
    provider: 'x402engine',
    baseUrl: 'https://x402-gateway-production.up.railway.app',
    path: '/api/travel/hotels',
    name: 'x402engine Hotel Search',
    description: 'Real-time hotel search via x402. Find available hotels with prices, ratings, and amenities. $0.02/request.',
    category: 'utility',
    costPerCall: 0.02,
    latencyMs: 3000,
    inputSchema: { location: 'City or landmark', checkIn: 'Check-in date (YYYY-MM-DD)', checkOut: 'Check-out date (YYYY-MM-DD)', guests: 'Number of guests (default 1)', stars: 'Minimum star rating 1-5 (optional)' },
    outputFields: ['hotels', 'name', 'price', 'rating', 'amenities', 'address', 'availability'],
  },
  {
    id: 'x402engine-ipfs-pin',
    provider: 'x402engine',
    baseUrl: 'https://x402-gateway-production.up.railway.app',
    path: '/api/ipfs/pin',
    name: 'x402engine IPFS Pin',
    description: 'Pin content to IPFS via x402 micropayments. $0.01/pin. Returns CID for permanent decentralized storage.',
    category: 'infrastructure',
    costPerCall: 0.01,
    latencyMs: 2000,
    inputSchema: { content: 'Content to pin (JSON, text, or URL)', name: 'Optional pin name' },
    outputFields: ['cid', 'size', 'url', 'timestamp'],
  },

  // ─── Blockchain/DeFi extras ─────────────────────────────────────────────────

  {
    id: 'x402engine-wallet',
    provider: 'x402engine',
    baseUrl: 'https://x402-gateway-production.up.railway.app',
    path: '/api/wallet/balances',
    name: 'x402engine Wallet Balances',
    description: 'Multi-chain wallet balances, token holdings, and PnL via x402. Supports EVM + Solana. $0.005/request.',
    category: 'defi',
    costPerCall: 0.005,
    latencyMs: 1000,
    inputSchema: { address: 'Wallet address (EVM or Solana)', chain: 'ethereum | base | polygon | solana | all (default: all)' },
    outputFields: ['tokens', 'totalValueUsd', 'nativeBalance', 'chain', 'lastUpdated'],
  },
  {
    id: 'x402engine-tx-simulate',
    provider: 'x402engine',
    baseUrl: 'https://x402-gateway-production.up.railway.app',
    path: '/api/tx/simulate',
    name: 'x402engine TX Simulate',
    description: 'Simulate a blockchain transaction before sending. Check for reverts, gas costs, and token flows. $0.01/simulation.',
    category: 'defi',
    costPerCall: 0.01,
    latencyMs: 1500,
    inputSchema: { from: 'Sender address', to: 'Target contract/address', data: 'Transaction calldata (hex)', value: 'ETH value in wei (optional)', chain: 'ethereum | base | polygon (default: ethereum)' },
    outputFields: ['success', 'gasUsed', 'gasEstimate', 'revertReason', 'stateChanges', 'tokenFlows'],
  },
];

export function registryToPromptContext(): string {
  const lines: string[] = ['Available API endpoints:\n'];
  for (const ep of apiRegistry) {
    lines.push(`[${ep.id}] ${ep.name} (${ep.category}) — Provider: ${ep.provider}`);
    lines.push(`  Description: ${ep.description}`);
    lines.push(`  Cost: $${ep.costPerCall} | Latency: ~${ep.latencyMs}ms`);
    lines.push(`  Inputs: ${JSON.stringify(ep.inputSchema)}`);
    lines.push(`  Outputs: ${ep.outputFields.join(', ')}`);
    lines.push('');
  }
  return lines.join('\n');
}

export function findEndpoint(id: string): ApiEndpoint | undefined {
  return apiRegistry.find((ep) => ep.id === id);
}

export function findByCategory(category: ApiEndpoint['category']): ApiEndpoint[] {
  return apiRegistry.filter((ep) => ep.category === category);
}

export function findByProvider(provider: string): ApiEndpoint[] {
  return apiRegistry.filter((ep) => ep.provider.toLowerCase().includes(provider.toLowerCase()));
}
